INSERT INTO [SandlerDB].[dbo].[TBL_OPPORTUNITYSTATUS]([Name])VALUES('Prospect');
INSERT INTO [SandlerDB].[dbo].[TBL_OPPORTUNITYSTATUS]([Name])VALUES('Assessment');
INSERT INTO [SandlerDB].[dbo].[TBL_OPPORTUNITYSTATUS]([Name])VALUES('Suspect');
GO

