
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TBL_SALES ADD
	Color varchar(50) NULL
GO
ALTER TABLE dbo.TBL_SALES SET (LOCK_ESCALATION = TABLE)
GO
UPDATE TBL_SALES SET Color = '009966' WHERE Id = 1;
UPDATE TBL_SALES SET Color = '9966FF' WHERE Id = 2;
UPDATE TBL_SALES SET Color = '8a4b08' WHERE Id = 3;
UPDATE TBL_SALES SET Color = '58fado' WHERE Id = 4;
UPDATE TBL_SALES SET Color = '0000FF' WHERE Id = 5;
UPDATE TBL_SALES SET Color = 'ff9900' WHERE Id = 6;
UPDATE TBL_SALES SET Color = 'ff33cc' WHERE Id = 7;
UPDATE TBL_SALES SET Color = '0afe47' WHERE Id = 8;
UPDATE TBL_SALES SET Color = 'ff3300' WHERE Id = 9;
UPDATE TBL_SALES SET Color = 'ffff00' WHERE Id = 10;
GO

COMMIT
