
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_MAIN ADD
	Color varchar(50) NULL,
	Link varchar(100) NULL
GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_MAIN SET (LOCK_ESCALATION = TABLE)
GO
UPDATE TBL_SALESCYCLETIME_MAIN SET Color = 'FF0000', Link = 'SCTDrill01.aspx' WHERE Id = 1;
UPDATE TBL_SALESCYCLETIME_MAIN SET Color = '00FF00', Link = 'SCTDrill02.aspx' WHERE Id = 2;
UPDATE TBL_SALESCYCLETIME_MAIN SET Color = 'FF00FF', Link = 'SCTDrill03.aspx' WHERE Id = 3;
UPDATE TBL_SALESCYCLETIME_MAIN SET Color = '0000FF', Link = 'SCTDrill04.aspx' WHERE Id = 4;
UPDATE TBL_SALESCYCLETIME_MAIN SET Color = 'F7d358', Link = 'SCTDrill05.aspx' WHERE Id = 5;
UPDATE TBL_SALESCYCLETIME_MAIN SET Color = '009966', Link = 'SCTDrill06.aspx' WHERE Id = 6;
GO

COMMIT
