
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_DRILL ADD
	Color varchar(50) NULL
GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_DRILL SET (LOCK_ESCALATION = TABLE)
GO
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = 'FF0000' WHERE Id = 1;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = '00FF00' WHERE Id = 2;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = 'FF00FF' WHERE Id = 3;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = '0000FF' WHERE Id = 4;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = '8A4B08' WHERE Id = 5;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = '009966'  WHERE Id = 6;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = '00AA00'  WHERE Id = 7;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = 'FFA0FF'  WHERE Id = 8;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = 'AA00FF'  WHERE Id = 9;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = '8A0008'  WHERE Id = 10;
UPDATE TBL_SALESCYCLETIME_DRILL SET Color = 'FF9966'  WHERE Id = 11
GO

COMMIT
