/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

USE [SANDLERDB]
GO

ALTER TABLE dbo.TBL_ASSESSMENTS ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_ASSESSMENTS ADD CONSTRAINT
	PK_TBL_ASSESSMENTS PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_ASSESSMENTS SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_COACHING ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_COACHING ADD CONSTRAINT
	PK_TBL_COACHING PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_COACHING SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_CONSULTING ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_CONSULTING ADD CONSTRAINT
	PK_TBL_CONSULTING PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_CONSULTING SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_CORPGLOBALTRAINING ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_CORPGLOBALTRAINING ADD CONSTRAINT
	PK_TBL_CORPGLOBALTRAINING PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_CORPGLOBALTRAINING SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_COSTOFSALE_DRILL ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_COSTOFSALE_DRILL ADD CONSTRAINT
	PK_TBL_COSTOFSALE_DRILL PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_COSTOFSALE_DRILL SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_COSTOFSALE_MAIN ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_COSTOFSALE_MAIN ADD CONSTRAINT
	PK_TBL_COSTOFSALE_MAIN PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_COSTOFSALE_MAIN SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_IND_AVERAGES ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_IND_AVERAGES ADD CONSTRAINT
	PK_TBL_IND_AVERAGES PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_IND_AVERAGES SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_LEADERSHIP ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_LEADERSHIP ADD CONSTRAINT
	PK_TBL_LEADERSHIP PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_LEADERSHIP SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_NEGOTIATIONS ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_NEGOTIATIONS ADD CONSTRAINT
	PK_TBL_NEGOTIATIONS PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_NEGOTIATIONS SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_NETWORKINGWORKS ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_NETWORKINGWORKS ADD CONSTRAINT
	PK_TBL_NETWORKINGWORKS PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_NETWORKINGWORKS SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_PIPELINE_POST ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PIPELINE_POST ADD CONSTRAINT
	PK_TBL_PIPELINE_POST PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PIPELINE_POST SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_PRDSALES_BYACT ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PRDSALES_BYACT ADD CONSTRAINT
	PK_TBL_PRDSALES_BYACT PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PRDSALES_BYACT SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_PRODSOLD_AS_SALE ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PRODSOLD_AS_SALE ADD CONSTRAINT
	PK_TBL_PRODSOLD_AS_SALE PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PRODSOLD_AS_SALE SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_PRODSOLD_BYCOMP ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PRODSOLD_BYCOMP ADD CONSTRAINT
	PK_TBL_PRODSOLD_BYCOMP PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PRODSOLD_BYCOMP SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_PRODSOLD_BYREP ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PRODSOLD_BYREP ADD CONSTRAINT
	PK_TBL_PRODSOLD_BYREP PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PRODSOLD_BYREP SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_PRODUCT_MARGIN ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PRODUCT_MARGIN ADD CONSTRAINT
	PK_TBL_PRODUCT_MARGIN PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PRODUCT_MARGIN SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_PROSPECTING ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_PROSPECTING ADD CONSTRAINT
	PK_TBL_PROSPECTING PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_PROSPECTING SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_RETENTION_RATE ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_RETENTION_RATE ADD CONSTRAINT
	PK_TBL_RETENTION_RATE PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_RETENTION_RATE SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_REVBYSOURCE ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_REVBYSOURCE ADD CONSTRAINT
	PK_TBL_REVBYSOURCE PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_REVBYSOURCE SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_SALES ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_SALES ADD CONSTRAINT
	PK_TBL_SALES PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_SALES SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_SALESCYCLETIME_DRILL ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_DRILL ADD CONSTRAINT
	PK_TBL_SALESCYCLETIME_DRILL PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_DRILL SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_SALESCYCLETIME_MAIN ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_MAIN ADD CONSTRAINT
	PK_TBL_SALESCYCLETIME_MAIN PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_SALESCYCLETIME_MAIN SET (LOCK_ESCALATION = TABLE)
GO
	
ALTER TABLE dbo.TBL_SALESTOTALBYMONTH ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_SALESTOTALBYMONTH ADD CONSTRAINT
	PK_TBL_SALESTOTALBYMONTH PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_SALESTOTALBYMONTH SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_SANDLERONLINE ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_SANDLERONLINE ADD CONSTRAINT
	PK_TBL_SANDLERONLINE PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_SANDLERONLINE SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.TBL_STRATEGICALLIANCIES ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_STRATEGICALLIANCIES ADD CONSTRAINT
	PK_TBL_STRATEGICALLIANCIES PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_STRATEGICALLIANCIES SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.TBL_STRATEGICCUSTCARE ADD
	Id int NOT NULL IDENTITY (1, 1)
GO
ALTER TABLE dbo.TBL_STRATEGICCUSTCARE ADD CONSTRAINT
	PK_TBL_STRATEGICCUSTCARE PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TBL_STRATEGICCUSTCARE SET (LOCK_ESCALATION = TABLE)
GO

COMMIT
