/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TBL_PROSPECTING ADD
	Color varchar(50) NULL
GO
ALTER TABLE dbo.TBL_PROSPECTING SET (LOCK_ESCALATION = TABLE)
GO

UPDATE dbo.TBL_PROSPECTING SET Color = '009966' WHERE Id = 1;
UPDATE dbo.TBL_PROSPECTING SET Color = '9966FF' WHERE Id = 2;
UPDATE dbo.TBL_PROSPECTING SET Color = 'f7d358' WHERE Id = 3;
UPDATE dbo.TBL_PROSPECTING SET Color = '58FADO' WHERE Id = 4;
UPDATE dbo.TBL_PROSPECTING SET Color = '0000FF' WHERE Id = 5;
COMMIT
