//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class Return_on_Trng_Investment
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> FranchiseeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public Nullable<int> YearDesignation { get; set; }
        public Nullable<decimal> InitialTrngInvestment { get; set; }
        public Nullable<decimal> ImplementationCost { get; set; }
        public Nullable<decimal> TrainingInvestment { get; set; }
        public Nullable<decimal> CostReductionSalesCycleTime { get; set; }
        public Nullable<decimal> CostReductionSalesEfficiency { get; set; }
        public Nullable<decimal> IncreasedQualifiedSales { get; set; }
        public Nullable<decimal> SavingsonRetainedSalesReps { get; set; }
        public Nullable<decimal> IncreasedQuotaAchievement { get; set; }
        public Nullable<decimal> TotalAnnualBenefits { get; set; }
        public Nullable<int> EstimatedBenefitsGained { get; set; }
        public Nullable<decimal> TotalBenefitsRealized { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> AnnualBenefitFlow { get; set; }
        public Nullable<decimal> CumBenefitFlow { get; set; }
        public Nullable<decimal> DiscountedCosts { get; set; }
        public Nullable<decimal> DiscountedBenefits { get; set; }
        public Nullable<decimal> TotalDiscountBenefitFlow { get; set; }
        public Nullable<decimal> TotalCumDiscountedBenefitFlow { get; set; }
        public Nullable<int> CostofCapital { get; set; }
        public Nullable<decimal> NetPresentValue { get; set; }
        public Nullable<int> Yr1ROI { get; set; }
        public Nullable<int> Yr2ROI { get; set; }
        public Nullable<int> Yr3ROI { get; set; }
        public string Payback { get; set; }
        public Nullable<decimal> OngoingSupportCosts { get; set; }
        public bool IsOriginalVersion { get; set; }
    }
    
}
