//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.TBL_COACH = new HashSet<TBL_COACH>();
            this.Tbl_FollowUpItemsList = new HashSet<Tbl_FollowUpItemsList>();
            this.TBL_FRANCHISEE_USERS = new HashSet<TBL_FRANCHISEE_USERS>();
            this.TBL_UserEmailGroup = new HashSet<TBL_UserEmailGroup>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual ICollection<TBL_COACH> TBL_COACH { get; set; }
        public virtual ICollection<Tbl_FollowUpItemsList> Tbl_FollowUpItemsList { get; set; }
        public virtual ICollection<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
        public virtual ICollection<TBL_UserEmailGroup> TBL_UserEmailGroup { get; set; }
    }
}
