//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    
    public partial class GetNewClientsWithProducts
    {
        public Nullable<int> CompaniesCount { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<decimal> TotalContractPrice { get; set; }
    }
}
