//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    
    public partial class GetNewAppointmentsWithAppointmentSource
    {
        public Nullable<int> ContactsCount { get; set; }
        public string ApptSourceName { get; set; }
    }
}
