//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    
    public partial class GetSalesCyclePortfolio
    {
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> OppCreationDate { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<int> DateDiffInMonths { get; set; }
        public Nullable<int> MultipleOfSix { get; set; }
    }
}
