//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageMenuGroup
    {
        public int pageMenuGroupId { get; set; }
        public Nullable<int> appId { get; set; }
        public string caption { get; set; }
        public string description { get; set; }
        public string iconPath { get; set; }
        public string iconClass { get; set; }
        public string pageMenuIds { get; set; }
        public string DefaultPage { get; set; }
        public string name { get; set; }
    }
}
