//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageMenu
    {
        public int pageMenuId { get; set; }
        public Nullable<int> appId { get; set; }
        public string name { get; set; }
        public string shortCaption { get; set; }
        public string longCaption { get; set; }
        public string description { get; set; }
        public string iconPath { get; set; }
        public string pagePath { get; set; }
        public string pageParams { get; set; }
        public Nullable<bool> isNewWindow { get; set; }
        public Nullable<bool> isModal { get; set; }
        public Nullable<bool> inIFRAME { get; set; }
        public string aElementIdentifier { get; set; }
    }
}
