//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class SandlerDBEntities : DbContext
    {
        public SandlerDBEntities()
            : base("name=SandlerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_AppointmentsSource> Tbl_AppointmentsSource { get; set; }
        public DbSet<Tbl_AwardLevel> Tbl_AwardLevel { get; set; }
        public DbSet<Tbl_BehindAmount> Tbl_BehindAmount { get; set; }
        public DbSet<TBL_BlastEmailGroup> TBL_BlastEmailGroup { get; set; }
        public DbSet<Tbl_CertifiedLevel> Tbl_CertifiedLevel { get; set; }
        public DbSet<TBL_CHART> TBL_CHART { get; set; }
        public DbSet<TBL_COACH> TBL_COACH { get; set; }
        public DbSet<TBL_COMPANIES> TBL_COMPANIES { get; set; }
        public DbSet<TBL_CONTACTS> TBL_CONTACTS { get; set; }
        public DbSet<Tbl_CostPlusAmount> Tbl_CostPlusAmount { get; set; }
        public DbSet<TBL_COUNTRY> TBL_COUNTRY { get; set; }
        public DbSet<Tbl_Course> Tbl_Course { get; set; }
        public DbSet<TBL_DOCS> TBL_DOCS { get; set; }
        public DbSet<Tbl_DocumentStatus> Tbl_DocumentStatus { get; set; }
        public DbSet<Tbl_FollowUpItemsList> Tbl_FollowUpItemsList { get; set; }
        public DbSet<TBL_FRANCHISEE> TBL_FRANCHISEE { get; set; }
        public DbSet<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
        public DbSet<Tbl_IndustryType> Tbl_IndustryType { get; set; }
        public DbSet<Tbl_MasterFranchisee> Tbl_MasterFranchisee { get; set; }
        public DbSet<Tbl_MeetingFrequencyType> Tbl_MeetingFrequencyType { get; set; }
        public DbSet<Tbl_MeetingType> Tbl_MeetingType { get; set; }
        public DbSet<TBL_OPPORTUNITIES> TBL_OPPORTUNITIES { get; set; }
        public DbSet<TBL_OpportunitiesHistory> TBL_OpportunitiesHistory { get; set; }
        public DbSet<TBL_OpportunitySource> TBL_OpportunitySource { get; set; }
        public DbSet<TBL_OPPORTUNITYSTATUS> TBL_OPPORTUNITYSTATUS { get; set; }
        public DbSet<TBL_OpportunityTypes> TBL_OpportunityTypes { get; set; }
        public DbSet<TBL_OpportunityWhyLost> TBL_OpportunityWhyLost { get; set; }
        public DbSet<Tbl_PrimaryBusiness> Tbl_PrimaryBusiness { get; set; }
        public DbSet<Tbl_ProductType> Tbl_ProductType { get; set; }
        public DbSet<Tbl_PurchaseLevel> Tbl_PurchaseLevel { get; set; }
        public DbSet<TBL_REGION> TBL_REGION { get; set; }
        public DbSet<Tbl_SandlerRole> Tbl_SandlerRole { get; set; }
        public DbSet<TBL_State> TBL_State { get; set; }
        public DbSet<TBL_Trng_Expenditure> TBL_Trng_Expenditure { get; set; }
        public DbSet<TBL_UserEmailGroup> TBL_UserEmailGroup { get; set; }
        public DbSet<Tbl_YesNoOptions> Tbl_YesNoOptions { get; set; }
        public DbSet<vw_Companies> vw_Companies { get; set; }
        public DbSet<vw_Contacts> vw_Contacts { get; set; }
        public DbSet<vw_Opportunities> vw_Opportunities { get; set; }
    
        public virtual ObjectResult<vw_Companies> GetCompaniesByUser(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Companies>("GetCompaniesByUser", userIdParameter);
        }
    
        public virtual ObjectResult<vw_Companies> GetCompaniesByUser(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Companies>("GetCompaniesByUser", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<vw_Contacts> GetContactsByUser(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Contacts>("GetContactsByUser", userIdParameter);
        }
    
        public virtual ObjectResult<vw_Contacts> GetContactsByUser(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Contacts>("GetContactsByUser", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<vw_Opportunities> GetOpportunitiesByUser(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Opportunities>("GetOpportunitiesByUser", userIdParameter);
        }
    
        public virtual ObjectResult<vw_Opportunities> GetOpportunitiesByUser(Nullable<System.Guid> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Opportunities>("GetOpportunitiesByUser", mergeOption, userIdParameter);
        }
    }
}
