//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ACEEmails
    {
        public int AceEmailId { get; set; }
        public int AceId { get; set; }
        public int EmailBankId { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.Guid> ScheduledBy { get; set; }
        public System.DateTime ScheduleDate { get; set; }
    }
}
