//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AceEmailTracker
    {
        public System.Guid ID { get; set; }
        public int AceId { get; set; }
        public string EmailAddress { get; set; }
        public bool IsViewed { get; set; }
    
        public virtual Tbl_AceMainInfo Tbl_AceMainInfo { get; set; }
    }
}
