//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FRANCHISEE
    {
        public TBL_FRANCHISEE()
        {
            this.TBL_COMPANIES = new HashSet<TBL_COMPANIES>();
            this.TBL_FRANCHISEE_USERS = new HashSet<TBL_FRANCHISEE_USERS>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CoachID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string WebAddress { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastCreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<bool> IsMasterFranchiseeExists { get; set; }
        public Nullable<int> MasterFranchiseeId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public Nullable<int> SandlerRoleId { get; set; }
        public string OfficePhone { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> AwardLevelId { get; set; }
        public Nullable<int> PurchaseLevelId { get; set; }
        public Nullable<int> CertifiedLevelId { get; set; }
        public Nullable<int> PrimaryBusinessId { get; set; }
        public Nullable<System.DateTime> InitialContractDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> ContractFormDate { get; set; }
        public Nullable<bool> IsContractorPermitted { get; set; }
        public Nullable<bool> IsSandlerMailRequired { get; set; }
        public Nullable<bool> IsKOLMember { get; set; }
        public Nullable<bool> IsAdvBoard { get; set; }
        public Nullable<bool> IsMktgCommittee { get; set; }
        public Nullable<bool> IsUsingSandlerCRM { get; set; }
        public Nullable<bool> IsDHSAwardWinner { get; set; }
        public Nullable<System.DateTime> DHSAwardDate { get; set; }
        public Nullable<System.DateTime> InitialTrngDate { get; set; }
        public Nullable<bool> IsReqToSubmitFinancial { get; set; }
        public Nullable<bool> IsRepAgreement { get; set; }
        public string WorkEmail { get; set; }
        public string WorkAddress { get; set; }
        public string WorkCity { get; set; }
        public Nullable<int> WorkStateId { get; set; }
        public string WorkZip { get; set; }
        public Nullable<int> WorkCountryId { get; set; }
        public string AlternateEmail { get; set; }
        public Nullable<bool> IsSameHomeAddress { get; set; }
        public string HomeAddress { get; set; }
        public string HomeCity { get; set; }
        public Nullable<int> HomeStateId { get; set; }
        public string HomeZip { get; set; }
        public Nullable<int> HomeCountryId { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<int> YearsWithCompany { get; set; }
        public Nullable<bool> IsCanPrintLocally { get; set; }
        public Nullable<bool> IsBuyFromCustomer { get; set; }
        public Nullable<bool> IsFixedPricePurchase { get; set; }
        public Nullable<bool> IsBehindInTerDev { get; set; }
        public Nullable<int> CostPlusAmountId { get; set; }
        public Nullable<int> BehindAmountId { get; set; }
        public string BusinessFocusArea { get; set; }
        public string ClosestMetroArea { get; set; }
        public string Territory { get; set; }
    
        public virtual TBL_COACH TBL_COACH { get; set; }
        public virtual ICollection<TBL_COMPANIES> TBL_COMPANIES { get; set; }
        public virtual TBL_COUNTRY TBL_COUNTRY { get; set; }
        public virtual ICollection<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
    }
}
