//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPPORTUNITIES
    {
        public TBL_OPPORTUNITIES()
        {
            this.TBL_DOCS = new HashSet<TBL_DOCS>();
            this.TBL_OpportunitiesHistory = new HashSet<TBL_OpportunitiesHistory>();
        }
    
        public int ID { get; set; }
        public int COMPANYID { get; set; }
        public int CONTACTID { get; set; }
        public string NAME { get; set; }
        public int ProductID { get; set; }
        public string SALESREPLASTNAME { get; set; }
        public string SALESREPFIRSTNAME { get; set; }
        public string SALESREPPHONE { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public string WINPROBABILITY { get; set; }
        public Nullable<decimal> WEIGHTEDVALUE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> OpportunityID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> WhyLostID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public Nullable<int> SeconadryContactId1 { get; set; }
        public Nullable<int> SeconadryContactId2 { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Pain { get; set; }
        public string LengthOfProblem { get; set; }
        public string Alternatives { get; set; }
        public string CostToFix { get; set; }
        public Nullable<bool> IsBudgeIdentified { get; set; }
        public Nullable<bool> IsMoveForward { get; set; }
        public Nullable<int> LU_CompanyStatusId { get; set; }
        public Nullable<int> LU_IndustrySubCategoryId { get; set; }
        public Nullable<int> LU_KAREDesignationId { get; set; }
        public Nullable<int> LU_POC1ApptSourceId { get; set; }
        public Nullable<int> LU_POC1CompanyRoleId { get; set; }
        public Nullable<int> LU_POC1NextActionStepId { get; set; }
        public Nullable<int> LU_POC1OpportunityRoleId { get; set; }
        public Nullable<int> LU_POC2ApptSourceId { get; set; }
        public Nullable<int> LU_POC2CompanyRoleId { get; set; }
        public Nullable<int> LU_POC2NextActionStepId { get; set; }
        public Nullable<int> LU_POC2OpportunityRoleId { get; set; }
        public Nullable<int> LU_POC3ApptSourceId { get; set; }
        public Nullable<int> LU_POC3CompanyRoleId { get; set; }
        public Nullable<int> LU_POC3NextActionStepId { get; set; }
        public Nullable<int> LU_POC3OpportunityRoleId { get; set; }
        public Nullable<int> LU_ProductServiceId { get; set; }
        public string POC1DISCDesignation { get; set; }
        public string POC1DiscussionTopic { get; set; }
        public string POC1Email { get; set; }
        public string POC1FirstName { get; set; }
        public Nullable<System.DateTime> POC1LastContactDate { get; set; }
        public string POC1LastName { get; set; }
        public string POC1MobilePhone { get; set; }
        public Nullable<System.DateTime> POC1NextContactDate { get; set; }
        public string POC1Notes { get; set; }
        public string POC1Phone { get; set; }
        public string POC2DISCDesignation { get; set; }
        public string POC2DiscussionTopic { get; set; }
        public string POC2Email { get; set; }
        public string POC2FirstName { get; set; }
        public Nullable<System.DateTime> POC2LastContactDate { get; set; }
        public string POC2LastName { get; set; }
        public string POC2MobilePhone { get; set; }
        public Nullable<System.DateTime> POC2NextContactDate { get; set; }
        public string POC2Notes { get; set; }
        public string POC2Phone { get; set; }
        public string POC3DISCDesignation { get; set; }
        public string POC3DiscussionTopic { get; set; }
        public string POC3Email { get; set; }
        public string POC3FirstName { get; set; }
        public Nullable<System.DateTime> POC3LastContactDate { get; set; }
        public string POC3LastName { get; set; }
        public string POC3MobilePhone { get; set; }
        public Nullable<System.DateTime> POC3NextContactDate { get; set; }
        public string POC3Notes { get; set; }
        public string POC3Phone { get; set; }
        public string column_a { get; set; }
        public string column_b { get; set; }
        public string column_c { get; set; }
        public string column_d { get; set; }
        public string column_e { get; set; }
        public Nullable<int> column_f { get; set; }
        public Nullable<int> column_g { get; set; }
        public Nullable<int> column_h { get; set; }
        public Nullable<int> column_i { get; set; }
        public Nullable<int> column_j { get; set; }
        public Nullable<System.DateTime> column_k { get; set; }
        public Nullable<System.DateTime> column_l { get; set; }
        public Nullable<System.DateTime> column_m { get; set; }
        public Nullable<System.DateTime> column_n { get; set; }
        public Nullable<System.DateTime> column_o { get; set; }
    
        public virtual TBL_COMPANIES TBL_COMPANIES { get; set; }
        public virtual ICollection<TBL_DOCS> TBL_DOCS { get; set; }
        public virtual TBL_OpportunitySource TBL_OpportunitySource { get; set; }
        public virtual TBL_OPPORTUNITYSTATUS TBL_OPPORTUNITYSTATUS { get; set; }
        public virtual TBL_OpportunityTypes TBL_OpportunityTypes { get; set; }
        public virtual TBL_OpportunityWhyLost TBL_OpportunityWhyLost { get; set; }
        public virtual Tbl_ProductType Tbl_ProductType { get; set; }
        public virtual ICollection<TBL_OpportunitiesHistory> TBL_OpportunitiesHistory { get; set; }
        public virtual TBL_CONTACTS TBL_CONTACTS { get; set; }
        public virtual TBL_CONTACTS TBL_CONTACTS1 { get; set; }
        public virtual TBL_CONTACTS TBL_CONTACTS2 { get; set; }
        public virtual LU_CompanyStatus LU_CompanyStatus { get; set; }
        public virtual LU_IndustrySubCategory LU_IndustrySubCategory { get; set; }
        public virtual LU_KAREDesignation LU_KAREDesignation { get; set; }
        public virtual LU_POC1ApptSource LU_POC1ApptSource { get; set; }
        public virtual LU_POC1CompanyRole LU_POC1CompanyRole { get; set; }
        public virtual LU_POC1NextActionStep LU_POC1NextActionStep { get; set; }
        public virtual LU_POC1OpportunityRole LU_POC1OpportunityRole { get; set; }
        public virtual LU_POC2ApptSource LU_POC2ApptSource { get; set; }
        public virtual LU_POC2CompanyRole LU_POC2CompanyRole { get; set; }
        public virtual LU_POC2NextActionStep LU_POC2NextActionStep { get; set; }
        public virtual LU_POC2OpportunityRole LU_POC2OpportunityRole { get; set; }
        public virtual LU_POC3ApptSource LU_POC3ApptSource { get; set; }
        public virtual LU_POC3CompanyRole LU_POC3CompanyRole { get; set; }
        public virtual LU_POC3NextActionStep LU_POC3NextActionStep { get; set; }
        public virtual LU_POC3OpportunityRole LU_POC3OpportunityRole { get; set; }
        public virtual LU_ProductService LU_ProductService { get; set; }
    }
}
