//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ACE_Campaign
    {
        public int ID { get; set; }
        public Nullable<int> CampaignTypeID { get; set; }
        public Nullable<int> FranchiseeID { get; set; }
        public string Name { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string EmailGroup { get; set; }
    
        public virtual Tbl_ACE_Campaign Tbl_ACE_Campaign1 { get; set; }
        public virtual Tbl_ACE_Campaign Tbl_ACE_Campaign2 { get; set; }
        public virtual Tbl_ACE_Campaign Tbl_ACE_Campaign11 { get; set; }
        public virtual Tbl_ACE_Campaign Tbl_ACE_Campaign3 { get; set; }
    }
}
