//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AceMainInfo
    {
        public Tbl_AceMainInfo()
        {
            this.Tbl_AceEmailTracker = new HashSet<Tbl_AceEmailTracker>();
        }
    
        public int AceId { get; set; }
        public string CampaignName { get; set; }
        public Nullable<short> CampaignTypeId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string CampaignPurpose { get; set; }
        public Nullable<short> MessageNumber { get; set; }
        public Nullable<int> DaysFromEvent { get; set; }
        public string MessageSubject { get; set; }
        public string Recipients { get; set; }
        public string EmailGroupIds { get; set; }
        public string ResponseTo { get; set; }
        public Nullable<short> CallToActionId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> MessageSentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> TotalCountOutBound { get; set; }
        public Nullable<int> TotalCountConfirm { get; set; }
        public string AttachFileName { get; set; }
    
        public virtual ICollection<Tbl_AceEmailTracker> Tbl_AceEmailTracker { get; set; }
    }
}
