//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PerformanceActuals
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> CallsMade { get; set; }
        public Nullable<int> MeetingsHeld { get; set; }
    }
}
