//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UserEmailGroup
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string GroupName { get; set; }
        public string CoachIds { get; set; }
        public string FrOwnerIds { get; set; }
        public string FrUsersIds { get; set; }
        public string FrContactsIds { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
