//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BlastEmailGroup
    {
        public int Id { get; set; }
        public string BlastGroupName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ForCorporate { get; set; }
        public Nullable<bool> ForCoach { get; set; }
        public Nullable<bool> ForFrOwner { get; set; }
        public Nullable<bool> ForFrUser { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
