//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandler.DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GA_Tracker
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ContactId { get; set; }
        public Nullable<int> AsIsSalesCycleTimeId { get; set; }
        public Nullable<int> AsIsSalesEffId { get; set; }
        public Nullable<int> AsIsSalesQualificationId { get; set; }
        public Nullable<int> AsIsQuotaAchtId { get; set; }
        public Nullable<int> ToBeSalesCycleTimeId { get; set; }
        public Nullable<int> ToBeSalesEffId { get; set; }
        public Nullable<int> ToBeSalesQualificationId { get; set; }
        public Nullable<int> ToBeQuotaAchtId { get; set; }
        public string DesiredAnnualImptSalesCycleTime { get; set; }
        public string DesiredAnnualImptSalesEfficiency { get; set; }
        public string DesiredAnnualImptSalesQualfn { get; set; }
        public string DesiredAnnualImptQuotaAcht { get; set; }
        public Nullable<decimal> Year1 { get; set; }
        public Nullable<decimal> Year2 { get; set; }
        public Nullable<decimal> Year3 { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> AsIsSalesRepRetnId { get; set; }
        public Nullable<int> ToBeSalesRepRetnId { get; set; }
        public Nullable<int> AsIsTrngBenefitsId { get; set; }
        public Nullable<int> ToBeTrngBenefitsId { get; set; }
        public string DesiredAnnualImptSalesRepRetention { get; set; }
        public string DesiredAnnualImptTrngBenefits { get; set; }
    
        public virtual TBL_COMPANIES TBL_COMPANIES { get; set; }
        public virtual TBL_CONTACTS TBL_CONTACTS { get; set; }
        public virtual TBL_GA_QuotaAchievement TBL_GA_QuotaAchievement { get; set; }
        public virtual TBL_GA_QuotaAchievement TBL_GA_QuotaAchievement1 { get; set; }
        public virtual TBL_GA_SalesCycleTime TBL_GA_SalesCycleTime { get; set; }
        public virtual TBL_GA_SalesCycleTime TBL_GA_SalesCycleTime1 { get; set; }
        public virtual TBL_GA_SalesEfficiency TBL_GA_SalesEfficiency { get; set; }
        public virtual TBL_GA_SalesEfficiency TBL_GA_SalesEfficiency1 { get; set; }
        public virtual TBL_GA_SalesQualification TBL_GA_SalesQualification { get; set; }
        public virtual TBL_GA_SalesQualification TBL_GA_SalesQualification1 { get; set; }
        public virtual TBL_GA_SalesRepRetention TBL_GA_SalesRepRetention { get; set; }
        public virtual TBL_GA_SalesRepRetention TBL_GA_SalesRepRetention1 { get; set; }
        public virtual TBL_GA_TrngBenefits TBL_GA_TrngBenefits { get; set; }
        public virtual TBL_GA_TrngBenefits TBL_GA_TrngBenefits1 { get; set; }
    }
}
