

SELECT p.ProductTypeName,o.WEIGHTEDVALUE, o.COMPANYID 
FROM TBL_OPPORTUNITIES o WITH(NOLOCK) 
INNER JOIN Tbl_ProductType p WITH(NOLOCK) ON p.Id = o.ProductId
INNER JOIN TBL_CONTACTS c WITH(nolock) ON c.CONTACTSID = o.CONTACTID
INNER JOIN TBL_COMPANIES cmp WITH(NOLOCK) ON cmp.CompaniesID = c.CompanyID
INNER JOIN TBL_FRANCHISEE f WITH(NOLOCK) ON f.ID = cmp.FranchiseeId
INNER JOIN TBL_COACH ch WITH(NOLOCK) ON f.CoachID = ch.ID
WHERE 
cmp.IsNewCompany = 1
AND o.ProductID <> 1
AND YEAR(o.CreatedDate) = YEAR(GETDATE()) 
AND MONTH(o.CreatedDate) = MONTH(DATEADD(MONTH,-2,GETDATE()))
AND ch.ID = 2;

SELECT SUM(o.WEIGHTEDVALUE)/5,COUNT( o.COMPANYID )
FROM TBL_OPPORTUNITIES o WITH(NOLOCK) 
INNER JOIN Tbl_ProductType p WITH(NOLOCK) ON p.Id = o.ProductId
INNER JOIN TBL_CONTACTS c WITH(nolock) ON c.CONTACTSID = o.CONTACTID
INNER JOIN TBL_COMPANIES cmp WITH(NOLOCK) ON cmp.CompaniesID = c.CompanyID
INNER JOIN TBL_FRANCHISEE f WITH(NOLOCK) ON f.ID = cmp.FranchiseeId
INNER JOIN TBL_COACH ch WITH(NOLOCK) ON f.CoachID = ch.ID
WHERE 
cmp.IsNewCompany = 1
AND o.ProductID <> 1
AND YEAR(o.CreatedDate) = YEAR(GETDATE()) 
AND MONTH(o.CreatedDate) = MONTH(DATEADD(MONTH,0,GETDATE()))
AND ch.ID = 2;