//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class C_Gap_Analysis_Training_Cost_Savings_
    {
        public string TrngCostSavings { get; set; }
        public Nullable<int> PercentofIndustryAve { get; set; }
        public int Id { get; set; }
    }
    
}
