//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class Gap_Analysis
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> FranchiseeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> RepID { get; set; }
        public string AsIs_SalesCycleTime { get; set; }
        public string AsIs_SalesEfficiency { get; set; }
        public string AsIs_SalesQualification { get; set; }
        public string AsIs_TrngCostSavings { get; set; }
        public string AsIs_QuotaAchievement { get; set; }
        public string AsIs_EstBenefitsGained { get; set; }
        public Nullable<int> AsIs_SalesCycleTimeofIndustryAve { get; set; }
        public Nullable<int> AsIs_SalesEfficiencyofIndustryAve { get; set; }
        public Nullable<int> AsIs_SalesQualificationofIndustryAve { get; set; }
        public Nullable<int> AsIs_TrngCostSavingsofIndustryAve { get; set; }
        public Nullable<int> AsIs_QuotaAchievementofIndustryAve { get; set; }
        public Nullable<int> AsIs_EstBenefitsGainedofIndustryAve { get; set; }
        public string ToBe_SalesCycleTime { get; set; }
        public string ToBe_SalesEfficiency { get; set; }
        public string ToBe_SalesQualification { get; set; }
        public string ToBe_TrngCostSavings { get; set; }
        public string ToBe_QuotaAchievement { get; set; }
        public string ToBe_EstBenefitsGained { get; set; }
        public Nullable<int> ToBe_SalesCycleTimeofIndustryAve { get; set; }
        public Nullable<int> ToBe_SalesEfficiencyofIndustryAve { get; set; }
        public Nullable<int> ToBe_SalesQualificationofIndustryAve { get; set; }
        public Nullable<int> ToBe_TrngCostSavingsofIndustryAve { get; set; }
        public Nullable<int> ToBe_QuotaAchievementofIndustryAve { get; set; }
        public Nullable<int> ToBe_EstBenefitsGainedofIndustryAve { get; set; }
    }
    
}
