//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class GATracker
    {
        public string AsIsEstBenefitsGained { get; set; }
        public string ToBeEstBenefitsGained { get; set; }
        public Nullable<int> ToBeEstBenefitsGainedPercentVal { get; set; }
        public string AsIsQuotaAchievement { get; set; }
        public string ToBeQuotaAchievement { get; set; }
        public Nullable<int> ToBeQuotaAchievementPercentVal { get; set; }
        public string AsIsSalesCycleTime { get; set; }
        public string ToBeSalesCycleTime { get; set; }
        public Nullable<int> ToBeSalesCycleTimePercentVal { get; set; }
        public string AsIsSalesEfficiency { get; set; }
        public string ToBeSalesEfficiency { get; set; }
        public Nullable<int> ToBeSalesEfficiencyPercentVal { get; set; }
        public string AsIsSalesQualification { get; set; }
        public string ToBeSalesQualification { get; set; }
        public Nullable<int> ToBeSalesQualificationPercentVal { get; set; }
        public string AsIsTrngCostSavings { get; set; }
        public string ToBeTrngCostSavings { get; set; }
        public Nullable<int> ToBeTrngCostSavingsPercentVal { get; set; }
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ContactId { get; set; }
        public Nullable<int> AsIsSalesCycleTimeId { get; set; }
        public Nullable<int> AsIsSalesEffId { get; set; }
        public Nullable<int> AsIsSalesQualificationId { get; set; }
        public Nullable<int> AsIsTrgCostSavingsId { get; set; }
        public Nullable<int> AsIsQuotaAchtId { get; set; }
        public Nullable<int> AsIsEstBenGainedId { get; set; }
        public Nullable<int> ToBeSalesCycleTimeId { get; set; }
        public Nullable<int> ToBeSalesEffId { get; set; }
        public Nullable<int> ToBeSalesQualificationId { get; set; }
        public Nullable<int> ToBeTrgCostSavingsId { get; set; }
        public Nullable<int> ToBeQuotaAchtId { get; set; }
        public Nullable<int> ToBeEstBenGainedId { get; set; }
        public string DesiredAnnualImptSalesCycleTime { get; set; }
        public string DesiredAnnualImptSalesEfficiency { get; set; }
        public string DesiredAnnualImptSalesQualfn { get; set; }
        public string DesiredAnnualImptTrgCstSvgs { get; set; }
        public string DesiredAnnualImptQuotaAcht { get; set; }
        public string DesiredAnnualImptEstBenefitsGained { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> AsIsEstBenefitsGainedPercentVal { get; set; }
        public Nullable<int> AsIsQuotaAchievementPercentVal { get; set; }
        public Nullable<int> AsIsSalesCycleTimePercentVal { get; set; }
        public Nullable<int> AsIsSalesEfficiencyPercentVal { get; set; }
        public Nullable<int> AsIsSalesQualificationPercentVal { get; set; }
        public Nullable<int> AsIsTrngCostSavingsPercentVal { get; set; }
        public Nullable<decimal> Year1 { get; set; }
        public Nullable<decimal> Year2 { get; set; }
        public Nullable<decimal> Year3 { get; set; }
    }
    
}
