//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace SandlerModels
{
    public partial class SandlerDBEntities : DbContext
    {
        public SandlerDBEntities()
            : base("name=SandlerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<TBL_BlastEmailGroup> TBL_BlastEmailGroup { get; set; }
        public DbSet<TBL_CHART> TBL_CHART { get; set; }
        public DbSet<TBL_COACH> TBL_COACH { get; set; }
        public DbSet<TBL_COUNTRY> TBL_COUNTRY { get; set; }
        public DbSet<Tbl_Course> Tbl_Course { get; set; }
        public DbSet<TBL_DOCS> TBL_DOCS { get; set; }
        public DbSet<Tbl_DocumentStatus> Tbl_DocumentStatus { get; set; }
        public DbSet<Tbl_FollowUpItemsList> Tbl_FollowUpItemsList { get; set; }
        public DbSet<TBL_OPPORTUNITYSTATUS> TBL_OPPORTUNITYSTATUS { get; set; }
        public DbSet<TBL_REGION> TBL_REGION { get; set; }
        public DbSet<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
        public DbSet<TBL_FRANCHISEE> TBL_FRANCHISEE { get; set; }
        public DbSet<Tbl_IndustryType> Tbl_IndustryType { get; set; }
        public DbSet<Tbl_ProductType> Tbl_ProductType { get; set; }
        public DbSet<Tbl_AppointmentsSource> Tbl_AppointmentsSource { get; set; }
        public DbSet<TBL_COMPANIES> TBL_COMPANIES { get; set; }
        public DbSet<TBL_OpportunitySource> TBL_OpportunitySource { get; set; }
        public DbSet<TBL_OpportunityTypes> TBL_OpportunityTypes { get; set; }
        public DbSet<TBL_OpportunityWhyLost> TBL_OpportunityWhyLost { get; set; }
        public DbSet<TBL_GA_QuotaAchievement> TBL_GA_QuotaAchievement { get; set; }
        public DbSet<TBL_GA_SalesCycleTime> TBL_GA_SalesCycleTime { get; set; }
        public DbSet<TBL_GA_SalesEfficiency> TBL_GA_SalesEfficiency { get; set; }
        public DbSet<TBL_GA_SalesQualification> TBL_GA_SalesQualification { get; set; }
        public DbSet<TBL_Trng_Expenditure> TBL_Trng_Expenditure { get; set; }
        public DbSet<TBL_CONTACTS> TBL_CONTACTS { get; set; }
        public DbSet<TBL_GA_SalesRepRetention> TBL_GA_SalesRepRetention { get; set; }
        public DbSet<TBL_GA_Tracker> TBL_GA_Tracker { get; set; }
        public DbSet<TBL_GA_TrngBenefits> TBL_GA_TrngBenefits { get; set; }
        public DbSet<TBL_OPPORTUNITIES> TBL_OPPORTUNITIES { get; set; }
    
        internal ObjectResult<Contact> GetContactsByUser(Nullable<System.Guid> userId)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Contact).Assembly);
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Contact>("GetContactsByUser", userIdParameter);
        }
    
        internal ObjectResult<Company> GetCompaniesByUser(Nullable<System.Guid> userId)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Company).Assembly);
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Company>("GetCompaniesByUser", userIdParameter);
        }
    
        internal ObjectResult<GATracker> GetGATrackerById(Nullable<int> gaId)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(GATracker).Assembly);
    
            var gaIdParameter = gaId.HasValue ?
                new ObjectParameter("gaId", gaId) :
                new ObjectParameter("gaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GATracker>("GetGATrackerById", gaIdParameter);
        }
    
        internal int DeleteContactsOfUser(Nullable<int> franchiseeId, Nullable<System.Guid> userId)
        {
            var franchiseeIdParameter = franchiseeId.HasValue ?
                new ObjectParameter("franchiseeId", franchiseeId) :
                new ObjectParameter("franchiseeId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteContactsOfUser", franchiseeIdParameter, userIdParameter);
        }
    
        internal ObjectResult<Opportunity> GetOpportunitiesByUser(Nullable<System.Guid> userId)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Opportunity).Assembly);
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Opportunity>("GetOpportunitiesByUser", userIdParameter);
        }
    }
}
