//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class Opportunity
    {
        public int RegionID { get; set; }
        public string Region { get; set; }
        public int CoachID { get; set; }
        public string CoachName { get; set; }
        public int FranchiseeId { get; set; }
        public string FranchiseeName { get; set; }
        public string ContactName { get; set; }
        public Nullable<bool> IsNewAppointment { get; set; }
        public Nullable<bool> IsRegisteredForTraining { get; set; }
        public Nullable<int> ApptSourceId { get; set; }
        public Nullable<System.DateTime> CourseTrainingDate { get; set; }
        public string PrimaryContactFirstName { get; set; }
        public string PrimaryContactLastName { get; set; }
        public string PrimaryContactEmail { get; set; }
        public string SeconadryContact1FirstName { get; set; }
        public string SeconadryContact1LastName { get; set; }
        public string SeconadryContact1Email { get; set; }
        public string SeconadryContact2FirstName { get; set; }
        public string SeconadryContact2LastName { get; set; }
        public string SeconadryContact2Email { get; set; }
        public string COMPANYNAME { get; set; }
        public Nullable<bool> IsNewCompany { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public string WhyLost { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string ProductTypeName { get; set; }
        public string Source { get; set; }
        public int ID { get; set; }
        public int COMPANYID { get; set; }
        public int CONTACTID { get; set; }
        public string NAME { get; set; }
        public int ProductID { get; set; }
        public string SALESREPLASTNAME { get; set; }
        public string SALESREPFIRSTNAME { get; set; }
        public string SALESREPPHONE { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public string WINPROBABILITY { get; set; }
        public Nullable<decimal> WEIGHTEDVALUE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> OpportunityID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> WhyLostID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public Nullable<int> SeconadryContactId1 { get; set; }
        public Nullable<int> SeconadryContactId2 { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<System.DateTime> OppCreationDate { get; set; }
    }
    
}
