//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class Opportunity
    {
        public int RegionID { get; set; }
        public string Region { get; set; }
        public int CoachID { get; set; }
        public string CoachName { get; set; }
        public int FranchiseeId { get; set; }
        public string FranchiseeName { get; set; }
        public string ContactName { get; set; }
        public Nullable<bool> IsNewAppointment { get; set; }
        public Nullable<bool> IsRegisteredForTraining { get; set; }
        public Nullable<int> ApptSourceId { get; set; }
        public Nullable<System.DateTime> CourseTrainingDate { get; set; }
        public string COMPANYNAME { get; set; }
        public Nullable<bool> IsNewCompany { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public int ID { get; set; }
        public int COMPANYID { get; set; }
        public int CONTACTID { get; set; }
        public string NAME { get; set; }
        public int ProductID { get; set; }
        public string SALESREPLASTNAME { get; set; }
        public string SALESREPFIRSTNAME { get; set; }
        public string SALESREPPHONE { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<int> VALUE { get; set; }
        public string WINPROBABILITY { get; set; }
        public Nullable<int> WEIGHTEDVALUE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> OpportunityID { get; set; }
    }
    
}
