//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_SALESCYCLETIME_DRILL
    {
        public string Category_Name { get; set; }
        public Nullable<int> Value_DL1 { get; set; }
        public Nullable<int> Value_DL2 { get; set; }
        public Nullable<int> Value_DL3 { get; set; }
        public Nullable<int> Value_DL4 { get; set; }
        public Nullable<int> Value_DL5 { get; set; }
        public Nullable<int> Value_DL6 { get; set; }
        public int Id { get; set; }
        public string Color { get; set; }
    }
    
}
