//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_PROSPECTING
    {
        public string FirstLevel_Name { get; set; }
        public Nullable<int> FirstLevel_Qty { get; set; }
        public string SecondLevel_Name { get; set; }
        public Nullable<int> SecondLevel_Qty { get; set; }
        public int Id { get; set; }
        public string Color { get; set; }
    }
    
}
