//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_OPPORTUNITY
    {
        public int OPP_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string OPP_NAME { get; set; }
        public Nullable<int> WEIGHTED_VALUE { get; set; }
        public string WIN_PROBABILITY { get; set; }
        public Nullable<int> TOTAL_VALUE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string ACCT_OPP_STATUS { get; set; }
        public Nullable<int> ACCT_ID { get; set; }
        public string SALES_REP { get; set; }
        public string REP_PHONE { get; set; }
        public string COMP_CONTACT { get; set; }
        public string COMP_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
    
}
