//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_DOCS
    {
        public int DOCSID { get; set; }
        public string DOCNAME { get; set; }
        public Nullable<int> OPPSID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string DOCUMENTSTATUS { get; set; }
        public Nullable<int> DOCSTATUSID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        internal Tbl_DocumentStatus Tbl_DocumentStatus { get; set; }
        internal TBL_COMPANIES TBL_COMPANIES { get; set; }
        internal TBL_OPPORTUNITIES TBL_OPPORTUNITIES { get; set; }
    }
    
}
