//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_RETENTION_RATE
    {
        public Nullable<int> Year { get; set; }
        public Nullable<int> Growth_Comp_Exp { get; set; }
        public Nullable<int> Mass_Mutual_Exp { get; set; }
        public Nullable<int> Marginal_Comp_Exp { get; set; }
        public Nullable<int> Growth_Comp_Effect { get; set; }
        public Nullable<int> Mass_Mutual_Effect { get; set; }
        public Nullable<int> Marginal_Comp_Effect { get; set; }
        public int Id { get; set; }
    }
    
}
