//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_COMPANY
    {
        public string COMPANY_NAME { get; set; }
        public int ID { get; set; }
        public string PRODUCT { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public Nullable<int> ACCOUNT_VALUE { get; set; }
        public Nullable<System.DateTime> LAST_CONTACT_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_CONTACT_DATE { get; set; }
        public string COMMENT { get; set; }
        public string ACTION_STEP { get; set; }
        public string SALES_REP { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> IndustryId { get; set; }
    }
    
}
