//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_COSTOFSALE_DRILL
    {
        public string Category_Name { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Profit { get; set; }
        public int Id { get; set; }
    }
    
}
