//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_REVBYSOURCE
    {
        public string Category_Name { get; set; }
        public Nullable<int> Value_2010 { get; set; }
        public Nullable<int> Value_2011 { get; set; }
        public Nullable<int> Value_2012 { get; set; }
        public Nullable<int> Qty_2010 { get; set; }
        public Nullable<int> Qty_2011 { get; set; }
        public Nullable<int> Qty_2012 { get; set; }
        public int Id { get; set; }
    }
    
}
