//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_FRANCHISEE
    {
        public TBL_FRANCHISEE()
        {
            this.TBL_COMPANIES = new HashSet<TBL_COMPANIES>();
            this.TBL_FRANCHISEE_USERS = new HashSet<TBL_FRANCHISEE_USERS>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CoachID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string WebAddress { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastCreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
    
        internal TBL_COACH TBL_COACH { get; set; }
        internal ICollection<TBL_COMPANIES> TBL_COMPANIES { get; set; }
        internal TBL_COUNTRY TBL_COUNTRY { get; set; }
        internal ICollection<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
    }
    
}
