//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_FORECAST
    {
        public int FORECAST_ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> Q2TOTAL { get; set; }
        public Nullable<int> Q3TOTAL { get; set; }
        public Nullable<int> Q4TOTAL { get; set; }
        public Nullable<int> YEAR { get; set; }
        public string SEASON_INDEX { get; set; }
        public string GROWTH_INDEX { get; set; }
        public string TRAINED_REPS { get; set; }
        public string SALES_CYCLE_TIME { get; set; }
        public Nullable<int> QuotaTotal { get; set; }
        public Nullable<int> BestCaseTotal { get; set; }
        public Nullable<int> SalesPLTotal { get; set; }
        public Nullable<long> Q2Quota { get; set; }
        public Nullable<long> Q2BestCase { get; set; }
        public Nullable<long> Q2SalesPL { get; set; }
        public Nullable<long> Q3Quota { get; set; }
        public Nullable<long> Q3BestCase { get; set; }
        public Nullable<long> Q3SalesPL { get; set; }
        public Nullable<long> Q4Quota { get; set; }
        public Nullable<long> Q4BestCase { get; set; }
        public Nullable<long> Q4SalesPL { get; set; }
    }
    
}
