//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_GA_Tracker
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ContactId { get; set; }
        public Nullable<int> AsIsSalesCycleTimeId { get; set; }
        public Nullable<int> AsIsSalesEffId { get; set; }
        public Nullable<int> AsIsSalesQualificationId { get; set; }
        public Nullable<int> AsIsTrgCostSavingsId { get; set; }
        public Nullable<int> AsIsQuotaAchtId { get; set; }
        public Nullable<int> AsIsEstBenGainedId { get; set; }
        public Nullable<int> ToBeSalesCycleTimeId { get; set; }
        public Nullable<int> ToBeSalesEffId { get; set; }
        public Nullable<int> ToBeSalesQualificationId { get; set; }
        public Nullable<int> ToBeTrgCostSavingsId { get; set; }
        public Nullable<int> ToBeQuotaAchtId { get; set; }
        public Nullable<int> ToBeEstBenGainedId { get; set; }
        public string DesiredAnnualImptSalesCycleTime { get; set; }
        public string DesiredAnnualImptSalesEfficiency { get; set; }
        public string DesiredAnnualImptSalesQualfn { get; set; }
        public string DesiredAnnualImptTrgCstSvgs { get; set; }
        public string DesiredAnnualImptQuotaAcht { get; set; }
        public string DesiredAnnualImptEstBenefitsGained { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        internal TBL_COMPANIES TBL_COMPANIES { get; set; }
        internal TBL_CONTACTS TBL_CONTACTS { get; set; }
        internal TBL_GA_EstBenefitsGained TBL_GA_EstBenefitsGained { get; set; }
        internal TBL_GA_EstBenefitsGained TBL_GA_EstBenefitsGained1 { get; set; }
        internal TBL_GA_QuotaAchievement TBL_GA_QuotaAchievement { get; set; }
        internal TBL_GA_QuotaAchievement TBL_GA_QuotaAchievement1 { get; set; }
        internal TBL_GA_SalesCycleTime TBL_GA_SalesCycleTime { get; set; }
        internal TBL_GA_SalesCycleTime TBL_GA_SalesCycleTime1 { get; set; }
        internal TBL_GA_SalesEfficiency TBL_GA_SalesEfficiency { get; set; }
        internal TBL_GA_SalesEfficiency TBL_GA_SalesEfficiency1 { get; set; }
        internal TBL_GA_SalesQualification TBL_GA_SalesQualification { get; set; }
        internal TBL_GA_SalesQualification TBL_GA_SalesQualification1 { get; set; }
        internal TBL_GA_TrainingCostSavings TBL_GA_TrainingCostSavings { get; set; }
        internal TBL_GA_TrainingCostSavings TBL_GA_TrainingCostSavings1 { get; set; }
    }
    
}
