//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class Tbl_ProductType
    {
        public Tbl_ProductType()
        {
            this.TBL_OPPORTUNITIES = new HashSet<TBL_OPPORTUNITIES>();
        }
    
        public int Id { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string LastUpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public string ColorCode { get; set; }
    
        internal ICollection<TBL_OPPORTUNITIES> TBL_OPPORTUNITIES { get; set; }
    }
    
}
