//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_DOCUMENTS
    {
        public int DOC_ID { get; set; }
        public string DOC_NAME { get; set; }
        public Nullable<int> OPP_ID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public string DOCUMENT_STATUS { get; set; }
        public string DOCUMENT_LOADED { get; set; }
        public string LastModifyBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
    
}
