//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_IND_AVERAGES
    {
        public string Category_Name { get; set; }
        public Nullable<int> Best_In_Class_Value { get; set; }
        public Nullable<int> Mass_Mutual_Value { get; set; }
        public Nullable<int> Ind_Avg_Value { get; set; }
        public int Id { get; set; }
    }
    
}
