//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_FRANCHISEE
    {
        public TBL_FRANCHISEE()
        {
            this.TBL_FRANCHISEE_USERS = new HashSet<TBL_FRANCHISEE_USERS>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int RegionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastCreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        public virtual TBL_REGION TBL_REGION { get; set; }
        public virtual ICollection<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
    }
    
}
