//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_OPPORTUNITIES
    {
        public TBL_OPPORTUNITIES()
        {
            this.TBL_DOCS = new HashSet<TBL_DOCS>();
        }
    
        public int ID { get; set; }
        public int COMPANYID { get; set; }
        public int CONTACTID { get; set; }
        public string NAME { get; set; }
        public int ProductID { get; set; }
        public string SALESREPLASTNAME { get; set; }
        public string SALESREPFIRSTNAME { get; set; }
        public string SALESREPPHONE { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<int> VALUE { get; set; }
        public string WINPROBABILITY { get; set; }
        public Nullable<decimal> WEIGHTEDVALUE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> OpportunityID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> WhyLostID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public Nullable<int> SeconadryContactId1 { get; set; }
        public Nullable<int> SeconadryContactId2 { get; set; }
    
        internal TBL_COMPANIES TBL_COMPANIES { get; set; }
        internal ICollection<TBL_DOCS> TBL_DOCS { get; set; }
        internal TBL_OpportunitySource TBL_OpportunitySource { get; set; }
        internal TBL_OPPORTUNITYSTATUS TBL_OPPORTUNITYSTATUS { get; set; }
        internal TBL_OpportunityTypes TBL_OpportunityTypes { get; set; }
        internal TBL_OpportunityWhyLost TBL_OpportunityWhyLost { get; set; }
        internal Tbl_ProductType Tbl_ProductType { get; set; }
        internal TBL_CONTACTS TBL_CONTACTS { get; set; }
        internal TBL_CONTACTS TBL_CONTACTS1 { get; set; }
        internal TBL_CONTACTS TBL_CONTACTS2 { get; set; }
    }
    
}
