//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_STRATEGICALLIANCIES
    {
        public string Label_Name { get; set; }
        public Nullable<int> P1_Value { get; set; }
        public Nullable<int> P2_Value { get; set; }
        public Nullable<int> P3_Value { get; set; }
        public Nullable<int> P1_Qty { get; set; }
        public Nullable<int> P2_Qty { get; set; }
        public Nullable<int> P3_Qty { get; set; }
        public int Id { get; set; }
    }
    
}
