//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_FRANCHISEE_USERS
    {
        public int FranchiseeID { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual TBL_FRANCHISEE TBL_FRANCHISEE { get; set; }
    }
    
}
