//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SandlerModels
{
    public partial class TBL_COUNTRY
    {
        public TBL_COUNTRY()
        {
            this.TBL_FRANCHISEE = new HashSet<TBL_FRANCHISEE>();
            this.TBL_FRANCHISEE_USERS = new HashSet<TBL_FRANCHISEE_USERS>();
            this.TBL_REGION = new HashSet<TBL_REGION>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<TBL_FRANCHISEE> TBL_FRANCHISEE { get; set; }
        public virtual ICollection<TBL_FRANCHISEE_USERS> TBL_FRANCHISEE_USERS { get; set; }
        public virtual ICollection<TBL_REGION> TBL_REGION { get; set; }
    }
    
}
