ALTER TABLE TBL_FRANCHISEE DROP COLUMN PhoneNumber;
GO
ALTER TABLE TBL_FRANCHISEE ADD PhoneNumber NVARCHAR(25)
GO
ALTER TABLE TBL_FRANCHISEE DROP COLUMN FaxNumber;
GO
ALTER TABLE TBL_FRANCHISEE ADD FaxNumber NVARCHAR(25)
GO
ALTER TABLE TBL_FRANCHISEE_USERS ADD [ID] [int] IDENTITY(1,1) NOT NULL
GO

ALTER TABLE TBL_FRANCHISEE_USERS ADD  CONSTRAINT [PK_TBL_FRANCHISEE_IsActive]  PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
GO