/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.3-release.4749
*/
(function(){var m=FusionCharts(["private","modules.renderer.highcharts-charts"]);if(m!==void 0){var m=m.hcLib,u=m.BLANKSTRING,ea=m.createTrendLine,g=m.pluck,J=m.getValidValue,n=m.pluckNumber,x=m.defaultPaletteOptions,ba=m.getFirstValue,ua=m.getDefinedColor,R=m.parseUnsafeString,H=m.FC_CONFIG_STRING,oa=m.extend2,pa=m.getDashStyle,va=m.toPrecision,wa=m.stubFN,fa=m.hasSVG,S=Math,E=S.sin,T=S.cos,K=S.PI/180,xa=m.graphics.getColumnColor,w=m.getFirstColor,ga=m.setLineHeight,qa=m.pluckFontSize,ca=m.getFirstAlpha,
ra=m.graphics.getDarkColor,ha=m.graphics.getLightColor,aa=m.graphics.convertColor,ia=m.COLOR_TRANSPARENT,ja=m.POSITION_CENTER,ya=m.POSITION_TOP,da=m.POSITION_BOTTOM,za=m.POSITION_RIGHT,Aa=m.POSITION_LEFT,c=m.chartAPI,Ba=m.titleSpaceManager,Ca=m.placeLegendBlockBottom,Da=m.placeLegendBlockRight,sa=m.graphics.mapSymbolName,S=c.singleseries,B=m.COMMASTRING,ta=m.STRINGUNDEFINED,O=m.ZEROSTRING,L=m.ONESTRING,M=m.HUNDREDSTRING,ka=m.PXSTRING,Ea=m.COMMASPACE;c("column2d",{standaloneInit:!0,creditLabel:!0},
c.column2dbase);c("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1},c.column2d);c("bar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:c.barbase},c.column2d);c("line",{standaloneInit:!0,creditLabel:!0},c.linebase);c("area2d",{standaloneInit:!0,creditLabel:!0},c.area2dbase);c("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,point:function(b,e,d,a,j){var o,f,p,l=j[H],h,i,c,m,r=0,t=0,q=[],k=g(a.plotborderthickness,L),s=n(a.use3dlighting,1)?n(a.radius3d,a["3dradius"],
90):100;p=n(a.showzeropies,1);var Z=!0,C=n(a.showpercentintooltip,1),v=n(a.showlabels,1),y=n(a.showvalues,1),la=n(a.showpercentvalues,a.showpercentagevalues,0),z=g(a.tooltipsepchar,a.hovercapsepchar,Ea),D=g(a.labelsepchar,z),G=g(a.plotbordercolor,a.piebordercolor),w=j[H].numberFormatter;h=d.length;var x;s>100&&(s=100);s<0&&(s=0);if(n(a.showlegend,0))j.legend.enabled=!0,j.legend.reversed=!Boolean(n(a.reverselegend,0)),e.showInLegend=!0;if(!v&&!y)j.plotOptions.series.dataLabels.enabled=!1,j.tooltip.enabled===
!1&&(Z=!1);for(b=0;b<h;b+=1)f=d[b],o=w.getCleanValue(f.value,!0),o===null||!p&&o===0||(q.push(f),r+=o);e.enableRotation=q.length>1?n(a.enablerotation,1):0;for(b=q.length-1;b>=0;b-=1){f=q[b];o=w.getCleanValue(f.value,!0);d=R(g(f.label,f.name,u));h=g(f.color,j.colors[b%j.colors.length]);i=g(f.alpha,a.plotfillalpha,M);c=g(f.bordercolor,G,ha(h,25)).split(B)[0];m=a.showplotborder==O?O:g(f.borderalpha,a.plotborderalpha,a.pieborderalpha,"80");p={opacity:Math.max(i,m)/100};if(x=Boolean(n(f.issliced,a.issliced,
0)))l.preSliced=x;e.data.push({showInLegend:d!==u,y:o,name:d,shadow:p,toolText:R(J(f.tooltext)),color:this.getPointColor(h,i,s),borderColor:aa(c,m),borderWidth:k,link:J(f.link),sliced:x,doNotSlice:g(a.enableslicing,L)!=L});if(Z)h=w.percentValue(o/r*100),i=w.dataLabels(o)||u,p=C===1?h:i,o=v===1?d:u,h=y===1?la===1?h:i:u,h=(f=J(f.displayvalue))?f:h!==u&&o!==u?o+D+h:g(o,h),d=d!=u?d+z+p:p,f=e.data[t],f.displayValue=h,f.toolText=g(f.toolText,d),t+=1}j.legend.enabled=a.showlegend==L?!0:!1;j.chart.startingAngle=
g(a.startingangle,0);return e},getPointColor:function(b,e,d){var a,j,b=w(b),e=ca(e);d<100&&fa?(a=Math.floor((100-0.35*d)*85)/100,a=ra(b,a),j=Math.floor((100+d)*50)/100,b=ha(b,j),e={FCcolor:{color:b+B+a,alpha:e+B+e,ratio:d+",100",radialGradient:!0}}):e={FCcolor:{color:b+B+b,alpha:e+B+e,ratio:"0,100"}};return e},configureAxis:function(b){var e=0,d=b[H],a;b.plotOptions.series.dataLabels.style=b.xAxis.labels.style;b.plotOptions.series.dataLabels.color=b.xAxis.labels.style.color;delete d.x;delete d[0];
delete d[1];b.chart.plotBorderColor=b.chart.plotBackgroundColor=ia;d=d.pieDATALabels=[];if(b.series.length===1&&(a=b.series[0].data)&&(e=b.series[0].data.length)>0&&b.plotOptions.series.dataLabels.enabled)for(;e--;)a[e]&&J(a[e].displayValue)!==void 0&&d.push(a[e].displayValue)},spaceManager:function(b,e,d,a){var j=b[H],o=this.name,f=j.smartLabel,p=n(j.pieDATALabels&&j.pieDATALabels.length,0),l=0,h=e.chart;n(h.managelabeloverflow,0);var i=!j.preSliced&&h.enableslicing==O&&(h.showlegend!=L||h.interactivelegend==
O)?0:n(h.slicingdistance,20),c=n(h.pieradius,0),m=n(h.enablesmartlabels,h.enablesmartlabel,1);n(h.skipoverlaplabels,h.skipoverlaplabel,1);var r=n(h.issmartlineslanted,1),t=n(h.labeldistance,h.nametbdistance,5),q=n(h.smartlabelclearance,5);d-=b.chart.marginRight+b.chart.marginLeft;var k=a-(b.chart.marginTop+b.chart.marginBottom),a=Math.min(k,d),s=g(h.smartlinecolor,x.plotFillColor[b.chart.paletteIndex]),u=n(h.smartlinealpha,100),C=n(h.smartlinethickness,1),v=b.plotOptions.series.dataLabels,a=c===0?
a*0.15:c,y=0,y=2*a;v.connectorWidth=C;v.connectorColor=aa(s,u);k-=Ba(b,e,d,y<k?k-y:k/2);h.showlegend==L&&(g(h.legendposition,da).toLowerCase()!=za?k-=Ca(b,e,d,k/2,!0):d-=Da(b,e,d/3,k,!0));for(f.setStyle(v.style);p--;)e=f.getOriSize(j.pieDATALabels[p]),l=Math.max(l,e.width);m&&(t=q+i);c===0&&(y=Math.min(d/2-l,k/2)-t,y>=a?a=y:t=Math.max(t-(a-y),i));b.plotOptions.pie.slicedOffset=i;b.plotOptions.pie.size=2*a;b.plotOptions.series.dataLabels.distance=t;b.plotOptions.series.dataLabels.isSmartLineSlanted=
r;b.plotOptions.series.dataLabels.enableSmartLabels=m;if(o==="doughnut2d"||o==="doughnut3d")if(j=n(h.doughnutradius,0),p=n(h.use3dlighting,1)?n(h.radius3d,h["3dradius"],50):100,p>100&&(p=100),p<0&&(p=0),h=j===0||j>=a?a/2:j,b.plotOptions.pie.innerSize=2*h,p>0&&fa&&(h=parseInt(h/a*100,10),j=(100-h)/2,p=parseInt(j*p/100,10),h=h+B+p+B+2*(j-p)+B+p,b.series[0]&&b.series[0].data)){o=b.series[0].data;b=0;for(p=o.length;b<p;b+=1)if(j=o[b],j.color.FCcolor)j.color.FCcolor.ratio=h}},creditLabel:!0,eiMethods:{togglePieSlice:function(b){var e=
this.jsVars.hcObj,d;if(e&&e.series&&(d=e.series[0])&&d.data&&d.data[b]&&d.data[b].slice)return d.data[d.xIncrement-1-b].slice()}}},S);c("pie3d",{defaultSeriesType:"pie",creditLabel:!0,defaultPlotShadow:0},c.pie2d);c("doughnut2d",{getPointColor:function(b,e,d){var a,b=w(b),e=ca(e);d<100&&fa?(a=Math.floor((85-0.2*(100-d))*100)/100,a=ra(b,a),d=Math.floor((100-0.5*d)*100)/100,b=ha(b,d),e={FCcolor:{color:a+B+b+B+b+B+a,alpha:e+B+e+B+e+B+e,radialGradient:!0}}):e=aa(b,e);return e}},c.pie2d);c("doughnut3d",
{defaultPlotShadow:0},c.doughnut2d);c("pareto2d",{standaloneInit:!0,point:function(b,e,d,a,j){var o,f,p,l,h,i,c,m,r,t,q,k,s,Z,C,b=d.length,v=0;i={};s=j.chart.paletteIndex;var y=/3d$/.test(j.chart.defaultSeriesType),la=this.isBar,z=g(360-a.plotfillangle,90),D=n(a.plotborderthickness,1),G=j.chart.useRoundEdges,Fa=g(a.tooltipsepchar,", "),ma=g(a.plotbordercolor,x.plotBorderColor[s]).split(B)[0],P=a.showplotborder==O?O:g(a.plotborderalpha,a.plotfillalpha,M),A=j.xAxis,K=n(a.showcumulativeline,1),E=j[H],
T=E.axisGridManager,S=E.x,V=a.showtooltip!=O,Q=[],na=[],L=n(a.use3dlighting,1),F=j[H].numberFormatter,U=n(a.showlinevalues,a.showvalues),P=y?a.showplotborder?P:O:P,ma=y?g(a.plotbordercolor,"#FFFFFF"):ma;for(k=f=0;f<b;f+=1)if(q=d[f],d[f].vline)T.addVline(A,q,k,j);else if(o=F.getCleanValue(q.value,!0),o!==null)q.value=o,Q.push(q),k+=1;b=Q.length;Q.sort(function(a,b){return b.value-a.value});if(K)c=n(a.linedashed,0),Z=w(g(a.linecolor,x.plotBorderColor[s])),f=g(a.linealpha,100),m=n(a.linedashlen,5),r=
n(a.linedashgap,4),i=n(a.linethickness,2),t={opacity:f/100},C=n(a.drawanchors,a.showanchors),C===void 0&&(C=f!=O),p=n(a.anchorborderthickness,1),h=n(a.anchorsides,0),l=n(a.anchorradius,3),k=w(g(a.anchorbordercolor,Z)),o=w(g(a.anchorbgcolor,x.anchorBgColor[s])),d=ca(g(a.anchoralpha,M)),q=ca(g(a.anchorbgalpha,d))*d/100,c=c?pa(m,r,i):void 0,i={yAxis:1,data:[],type:"line",color:aa(Z,f),lineWidth:i,marker:{enabled:C,fillColor:aa(o,q),lineColor:aa(k,d),lineWidth:p,radius:l,symbol:sa(h),startAngle:g(a.anchorstartangle,
90)}};else{if(a.showsecondarylimits!=="1")a.showsecondarylimits="0";if(a.showdivlinesecondaryvalue!=="1")a.showdivlinesecondaryvalue="0"}for(f=0;f<b;f+=1)q=Q[f],o=n(q.showlabel,a.showlabels,1),d=R(!o?u:ba(q.label,q.name)),T.addXaxisCat(A,f,f,d),v+=o=q.value,p=g(q.color,j.colors[f%j.colors.length])+B+ua(a.plotgradientcolor,x.plotGradientColor[s]),l=g(q.alpha,a.plotfillalpha,M),h=g(q.ratio,a.plotfillratio),k={opacity:l/100},Z=g(q.alpha,P)+u,p=xa(p,l,h,z,G,ma,Z,la,y),e.data.push(oa(this.getPointStub(q,
o,d,j),{y:o,shadow:k,color:p[0],borderColor:p[1],borderWidth:D,use3DLighting:L})),this.pointValueWatcher(j,o),K&&na.push({value:v,dataLabel:d,tooltext:J(q.tooltext)});S.catCount=b;E[1]||(E[1]={});E[1].stacking100Percent=!0;if(K&&v>0){f=0;for(b=na.length;f<b;f+=1)q=na[f],j=e.data[f],o=q.value/v*100,s=F.percentValue(o),a=j.displayValue!==u?s:u,U==1&&(a=s),U==0&&(a=u),d=q.dataLabel,s=V?q.tooltext!==void 0?q.tooltext:(d!==u?d+Fa:u)+s:u,i.data.push({shadow:t,y:o,toolText:s,displayValue:a,link:j.link,dashStyle:c});
return[e,i]}else return e},defaultSeriesType:"column",isDual:!0,creditLabel:!0},S);c("pareto3d",{defaultSeriesType:"column3d",defaultPlotShadow:1},c.pareto2d);c("mscolumn2d",{standaloneInit:!0,creditLabel:!0},c.mscolumn2dbase);c("mscolumn3d",{defaultSeriesType:"column3d",defaultPlotShadow:1},c.mscolumn2d);c("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:c.barbase},c.mscolumn2d);c("msbar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1},c.msbar2d);c("msline",{standaloneInit:!0,creditLabel:!0},
c.mslinebase);c("msarea",{standaloneInit:!0,creditLabel:!0},c.msareabase);c("stackedcolumn2d",{isStacked:!0},c.mscolumn2d);c("stackedcolumn3d",{isStacked:!0},c.mscolumn3d);c("stackedbar2d",{isStacked:!0},c.msbar2d);c("stackedbar3d",{isStacked:!0},c.msbar3d);c("stackedarea2d",{isStacked:!0,showSum:0},c.msarea);c("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:wa,postSeriesAddition:function(b,e){var d=b[H],a,j,o,f,p,l=0;f=b.xAxis;var h,i=100/d.marimekkoTotal,c=[],g=b.series,
r,m=0,q,k=n(e.chart.plotborderthickness,1),s=b.chart.rotateValues,u=n(e.chart.rotatexaxispercentvalues,0),k=k*-0.5-(k%2+(u?0:4)),C=u?3:0,v=s?270:0;j=d[0];var y=!j.stacking100Percent,w=d.inCanvasStyle;d.isXYPlot=!0;d.distributedColumns=!0;f.min=0;f.max=100;f.labels.enabled=!1;f.gridLineWidth=0;f.alternateGridColor=ia;a=j.stack;e.chart.interactivelegend="0";p=0;for(j=b.xAxis.plotLines.length;p<j;p+=1)if(h=f.plotLines[p],h.isGrid)h.isCat=!0,c[h.value]=h;if(a.floatedcolumn&&(o=a.floatedcolumn[0])){a=
0;for(j=o.length;a<j;){l+=f=o[a].p||0;r=f*i;h=m+r/2;q=m+r;for(p=0;p<g.length;p+=1)b.series[p].data[a]._FCX=m,b.series[p].data[a]._FCW=r;d.showStackTotal&&b.xAxis.plotLines.push({value:h,width:0,isVline:y,isTrend:!y,label:{align:ja,textAlign:v,rotation:s?270:0,style:d.trendStyle,verticalAlign:ya,y:0,x:0,text:this.numberFormatter.yAxis(va(f,10))}});if(c[a])c[a].value=h,c[a]._weight=r;a+=1;d.showXAxisPercentValues&&a<j&&b.xAxis.plotLines.push({value:q,width:0,isVine:!0,label:{align:ja,textAlign:u?Aa:
ja,rotation:u?270:0,style:{color:w.color,fontSize:w.fontSize,fontFamily:w.fontFamily,lineHeight:w.lineHeight,border:"1px solid",borderColor:w.color,backgroundColor:"#ffffff",backgroundOpacity:1},verticalAlign:da,y:k,x:C,text:this.numberFormatter.percentValue(q)},zIndex:5});m=q}}},defaultSeriesType:"floatedcolumn"},c.stackedcolumn2d);c("msstackedcolumn2d",{series:function(b,e,d){var a,j,o,f,p=e[H],l=0,h,i;h=[];var g;e.legend.enabled=Boolean(n(b.chart.showlegend,1));if(b.dataset&&b.dataset.length>0){this.categoryAdder(b,
e);a=0;for(j=b.dataset.length;a<j;a+=1)if(g=b.dataset[a].dataset){o=0;for(f=g.length;o<f;o+=1,l+=1)h={data:[],stack:a},i=Math.min(p.oriCatTmp.length,g[o].data&&g[o].data.length),h=this.point(d,h,g[o],b.chart,e,i,l,a),e.series.push(h)}if(this.isDual&&b.lineset&&b.lineset.length>0){o=0;for(f=b.lineset.length;o<f;o+=1,l+=1)h={data:[],yAxis:1,type:"line"},d=b.lineset[o],i=Math.min(p.oriCatTmp.length,d.data&&d.data.length),e.series.push(c.msline.point.call(this,"msline",h,d,b.chart,e,i,l))}this.configureAxis(e,
b);b.trendlines&&ea(b.trendlines,e.yAxis,e[H],!1,this.isBar)}}},c.stackedcolumn2d);c("mscombi2d",{series:function(b,e,d){var a,j,o,f,p=b.chart,l,h=[],i=[],I=[],m,r,t=e[H],q=this.isDual;e.legend.enabled=Boolean(n(b.chart.showlegend,1));if(b.dataset&&b.dataset.length>0){this.categoryAdder(b,e);f=t.oriCatTmp.length;a=0;for(j=b.dataset.length;a<j;a+=1){o=b.dataset[a];m=q&&g(o.parentyaxis,"p").toLowerCase()==="s"?!0:!1;l={data:[]};if(m)l.yAxis=1;r=ba(o.renderas,u).toLowerCase();switch(r){case "line":l.type=
"line";h.push(c.msline.point.call(this,d,l,o,p,e,f,a));break;case "area":l.type="area";e.chart.series2D3Dshift=!0;I.push(c.msarea.point.call(this,d,l,o,p,e,f,a));break;case "column":i.push(c.mscolumn2d.point.call(this,d,l,b.dataset[a],p,e,f,a));break;default:m?(l.type="line",h.push(c.msline.point.call(this,d,l,o,p,e,f,a))):i.push(c.mscolumn2d.point.call(this,d,l,b.dataset[a],p,e,f,a))}}e.series=p.areaovercolumns!=="0"?e.series.concat(i,I,h):e.series.concat(I,i,h);if(i.length===0)t.hasNoColumn=!0;
this.configureAxis(e,b);b.trendlines&&ea(b.trendlines,e.yAxis,e[H],!1,this.isBar)}}},c.mscolumn2d);c("mscombi3d",{series:c.mscombi2d.series,eiMethods:"view2D,view3D,resetView,rotateView,getViewAngles,fitToStage"},c.mscolumn3d);c("mscolumnline3d",{},c.mscombi3d);c("stackedcolumn2dline",{isStacked:!0,stack100percent:0},c.mscombi2d);c("stackedcolumn3dline",{isStacked:!0,stack100percent:0},c.mscombi3d);c("mscombidy2d",{isDual:!0},c.mscombi2d);c("mscolumn3dlinedy",{isDual:!0},c.mscolumnline3d);c("stackedcolumn3dlinedy",
{isDual:!0},c.stackedcolumn3dline);c("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0},c.msstackedcolumn2d);c("scrollcolumn2d",{postSeriesAddition:c.scrollbase.postSeriesAddition,avgScrollPointWidth:40},c.mscolumn2d);c("scrollline2d",{postSeriesAddition:c.scrollbase.postSeriesAddition,avgScrollPointWidth:75},c.msline);c("scrollarea2d",{postSeriesAddition:c.scrollbase.postSeriesAddition,avgScrollPointWidth:75},c.msarea);c("scrollstackedcolumn2d",{postSeriesAddition:function(b,e,d,a){c.base.postSeriesAddition.call(this,
b,e,d,a);c.scrollbase.postSeriesAddition.call(this,b,e,d,a)},avgScrollPointWidth:75},c.stackedcolumn2d);c("scrollcombi2d",{postSeriesAddition:c.scrollbase.postSeriesAddition,avgScrollPointWidth:40},c.mscombi2d);c("scrollcombidy2d",{postSeriesAddition:c.scrollbase.postSeriesAddition,avgScrollPointWidth:40},c.mscombidy2d);c("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",creditLabel:!0},c.scatterbase);c("bubble",{standaloneInit:!0,standaloneInut:!0,defaultSeriesType:"bubble",point:function(b,
e,d,a,j,o,f){if(d.data){var p,l,h,i,I,m,r,t,q,k,s=!1,u,C,b=c[b],o=d.data,v=o.length,y=n(d.showvalues,j[H].showValues);h=n(a.bubblescale,1);var x=g(a.negativecolor,"FF0000"),z=j.plotOptions.bubble,D=this.numberFormatter,G=n(d.showregressionline,a.showregressionline,0);z.bubbleScale=h;e.name=J(d.seriesname);if(n(d.includeinlegend)===0||e.name===void 0)e.showInLegend=!1;h=Boolean(n(d.drawanchors,d.showanchors,a.drawanchors,1));r=g(d.plotfillalpha,d.bubblefillalpha,a.plotfillalpha,M);t=n(d.showplotborder,
a.showplotborder,1);q=w(g(d.plotbordercolor,a.plotbordercolor,"666666"));p=g(d.plotborderthickness,a.plotborderthickness,1);k=g(d.plotborderalpha,a.plotborderalpha,"95");t=t==1?p:0;f=g(d.color,d.plotfillcolor,a.plotfillcolor,j.colors[f%j.colors.length]);e.marker={enabled:h,fillColor:this.getPointColor(f,M),lineColor:{FCcolor:{color:q,alpha:k}},lineWidth:t,symbol:"circle"};if(G){e.events={hide:this.hideRLine,show:this.showRLine};var B={sumX:0,sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},
E=n(d.showyonx,a.showyonx,1),P=w(g(d.regressionlinecolor,a.regressionlinecolor,f)),A=n(d.regressionlinethickness,a.regressionlinethickness,1);p=ca(n(d.regressionlinealpha,a.regressionlinealpha,100));P=aa(P,p)}for(l=0;l<v;l+=1)if(i=o[l])if(p=D.getCleanValue(i.y),u=D.getCleanValue(i.x),C=D.getCleanValue(i.z,!0),p===null)e.data.push({y:null,x:u});else{s=!0;I=w(g(i.color,i.z<0?x:f));m=g(i.alpha,r);i=b.getPointStub(i,p,u,j,d,y);I=n(a.use3dlighting)===0?I:b.getPointColor(I,m);if(C!==null)z.zMax=z.zMax>
C?z.zMax:C,z.zMin=z.zMin<C?z.zMin:C;e.data.push({y:p,x:u,z:C,displayValue:i.displayValue,toolText:i.toolText,link:i.link,marker:{enabled:h,fillColor:I,lineColor:{FCcolor:{color:q,alpha:k}},lineWidth:t,symbol:"circle"}});this.pointValueWatcher(j,p,u,G&&B)}else e.data.push({y:null});G&&(d={type:"line",color:P,showInLegend:!1,lineWidth:A,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(B,E,v),zIndex:0},e=[e,d])}if(!s)e.showInLegend=!1;return e},getPointStub:function(b,e,d,
a,j,o){var a=a[H],e=e===null?e:a.numberFormatter.dataLabels(e),f,c=a.tooltipSepChar;a.showTooltip?J(b.tooltext)!==void 0?j=R(b.tooltext):e===null?j=!1:(a.seriesNameInToolTip&&(f=g(j&&j.seriesname)),j=f?f+c:u,j+=d?d+c:u,j+=e,j+=b.z?c+b.z:u):j=u;d=n(b.showvalue,o,a.showValues)?g(b.name,b.label)!==void 0?R(g(b.name,b.label)):e:u;b=J(b.link);return{displayValue:d,toolText:j,link:b}}},c.scatter);c("zoomline",{standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",chart:function(){var b=this.dataObj.chart,
e=this.base.chart.apply(this,arguments);!J(b.caption)&&!J(b.subcaption)&&(e.chart.marginTop+=15);e.chart.animation=!1;(e.plotOptions||(e.plotOptions={}))&&(e.plotOptions.series||(e.plotOptions.series={}));e.plotOptions.series.animation=!1;return e},xAxisMinMaxSetter:function(b){this.base.xAxisMinMaxSetter.apply(this,arguments);var e=b.xAxis,d=b[H].x;e.min=0;e.max=d.catCount-1},series:function(b,e,d){var a,j,o=e[H],f;a=b.chart;n(a.compactdatamode,0);e.legend.enabled=Boolean(n(a.showlegend,1));if(b.dataset&&
b.dataset.length>0){b.categories&&b.categories[0]&&b.categories[0].category&&this.categoryAdder(b,e);a=0;for(j=b.dataset.length;a<j;a+=1)if(b.dataset[a].data)f={data:[]},f=this.point(d,f,b.dataset[a],b.chart,e,o.oriCatTmp.length,a),f instanceof Array?e.series=e.series.concat(f):e.series.push(f),f=!0;f&&(this.configureAxis(e,b),b.trendlines&&!this.isLog&&ea(b.trendlines,e.yAxis,o,!1,this.isBar))}},point:function(b,e,d,a,j,o,f){var c,l,h,i,I,m,r,t,q,k,s,x,C,v,y,B,z,D,G=d.data,E=j[H],b=g(e.type,this.defaultSeriesType),
J=j.plotOptions[b]&&j.plotOptions[b].stacking,P=g(this.isValueAbs,E.isValueAbs,!1);n(d.showvalues,E.showValues);var E=n(e.yAxis,0),A=this.numberFormatter;t=n(a.compactdatamode,0);D=g(a.dataseparator,"|");c=g(d.seriesname,u);l=w(g(d.color,a.linecolor,j.colors[f%j.colors.length]));h=g(d.alpha,a.linealpha,M);i=n(d.linethickness,a.linethickness,2);I=Boolean(n(d.dashed,a.linedashed,0));m=n(d.linedashlen,a.linedashlen,5);r=n(d.linedashgap,a.linedashgap,4);n(d.includeinlegend,1);g(d.valueposition,a.valueposition);
f=n(d.showvalues,a.showvalues);q=n(d.drawanchors,d.showanchors,a.drawanchors,a.showanchors);k=n(d.anchorsides,a.anchorsides,0);s=n(d.anchorradius,a.anchorradius,3);x=w(g(d.anchorbordercolor,a.anchorbordercolor,l));C=n(d.anchorborderthickness,a.anchorborderthickness,1);v=w(g(d.anchorbgcolor,a.anchorbgcolor,l));y=g(d.anchoralpha,a.anchoralpha,M);a=g(d.anchorbgalpha,a.anchorbgalpha,y);e.marker={enabled:q===void 0?h!=0:!!q,fillColor:{FCcolor:{color:v,alpha:a*y/100+u}},lineColor:{FCcolor:{color:x,alpha:y+
u}},lineWidth:C,radius:s,symbol:sa(k)};e.name=c;e.color={FCcolor:{color:l,alpha:h}};e.lineWidth=i;e.dashStyle=I?pa(m,r,i):void 0;if(n(d.includeinlegend)===0||e.name===void 0||h==0&&q!==1)e.showInLegend=!1;if(G)if(t){G=G[0].split(D);i={opacity:z/100};for(d=0;d<o;d+=1)c=A.getCleanValue(G[d]),c===null?e.data.push({y:null}):(B=!0,t=A.dataLabels(c),I=f?t:u,e.data.push({y:c,displayValue:I,shadow:i,toolText:t}),this.pointValueWatcher(j,c,E,J,d,0,b))}else for(d=0;d<o;d+=1)(z=G[d])?(c=A.getCleanValue(z.value,
P),c===null?e.data.push({y:null}):(B=!0,n(z.anchorsides,k),n(z.anchorradius,s),w(g(z.anchorbordercolor,x)),n(z.anchorborderthickness,C),w(g(z.anchorbgcolor,v)),g(z.anchoralpha,y),g(z.anchorbgalpha,a),D=w(g(z.color,l)),z=g(z.alpha,h),i={opacity:z/100},t=A.dataLabels(c),I=f?t:u,e.data.push({displayValue:I,toolText:t,y:c,shadow:i,color:{FCcolor:{color:D,alpha:z}}}),this.pointValueWatcher(j,c,E,J,d,0,b))):e.data.push({y:null});if(!B)e.showInLegend=!1;return e},categoryAdder:function(b,e){var d,a=0,j,
o=e[H],f=o.axisGridManager,c=e.xAxis,l,h=o.x,i=b.chart,I=e.chart,m=n(i.showlabels,1);I.zoomType="x";c.maxZoom=2;j=n(i.pixelsperpoint,15);j<=0&&(j=15);o.pixelsperpoint=j;if(b.categories&&b.categories[0]&&b.categories[0].category){if(b.categories[0].font)e.xAxis.labels.style.fontFamily=b.categories[0].font;if((j=n(b.categories[0].fontsize))!==void 0)j<1&&(j=1),e.xAxis.labels.style.fontSize=j+ka,ga(e.xAxis.labels.style);if(b.categories[0].fontcolor)e.xAxis.labels.style.color=b.categories[0].fontcolor.split(B)[0].replace(/^\#?/,
"#");j=e[H].oriCatTmp;var r=b.categories[0].category;d=n(i.compactdatamode,0);l=g(i.dataseparator,"|");if(d){f=r[0].split(l);for(d=0;d<f.length;d+=1)l=R(ba(f[d],f[d].name)),j[a]=l,a+=1}else for(d=0;d<r.length;d+=1)r[d].vline?f.addVline(c,r[d],a):(l=r[d].showlabel==="0"?u:R(ba(b.categories[0].category[d].label,b.categories[0].category[d].name)),j[a]=ba(R(b.categories[0].category[d].tooltext),l),a+=1);if(m)c.categories=j}c=a-1;o.displayStartIndex=n(i.displaystartindex,0);o.displayEndIndex=n(i.displayendindex,
c);if(o.displayStartIndex<0||o.displayStartIndex>=c)o.displayStartIndex=0;if(o.displayEndIndex<=o.displayStartIndex||o.displayEndIndex>c)o.displayEndIndex=c;h.catCount=a;I.hasScroll=!0;a=I.stepZoom={};a.pixelsperpoint=o.pixelsperpoint;a.displayStartIndex=o.displayStartIndex;a.displayEndIndex=o.displayEndIndex;a.scrollColor=w(g(i.scrollcolor,x.altHGridColor[e.chart.paletteIndex]));a.scrollHeight=n(i.scrollheight,16);a.scrollPadding=n(i.scrollpadding,e.chart.plotBorderWidth);a.scrollBtnWidth=n(i.scrollbtnwidth,
i.scrollheight,16);a.scrollBtnPadding=n(i.scrollbtnpadding,0);o.marginBottomExtraSpace+=a.scrollPadding+a.scrollHeight},placeHorizontalAxis:function(b,e,d,a,j,c,f){var p=d[H],l,h,i,g,m,r,t,q=0,k=0,s=10,w=1,C=0,v=0,y=!1,x=!1,z=!1;i=n(a.chart.labelstep,0);t=e.labelDisplay;var D=e.rotateLabels,G=e.horizontalLabelPadding,B=p.marginBottomExtraSpace,E=d.chart.marginLeft,P=d.chart.marginRight,A=p.smartLabel,K=p.pixelsperpoint,T=e.catCount,M=e.slantLabels,O=j/(b.max-b.min),V=0,Q=0,v={w:0,h:0};if(b.labels.style)m=
b.labels.style,A.setStyle(m),h=A.getOriSize("W"),s=h.height,r=h.width+4,g=A.getOriSize("WWW").width+4;var R,S,F,U=[],L=[],W=0,X=0,N,$=e.horizontalAxisNamePadding;F=0;var e=e.staggerLines,Y=V;if(b.title&&b.title.text!=u)m=b.title.style,A.setStyle(m),C=A.getOriSize("W").height,b.title.rotation=0,h=A.getSmartText(b.title.text,j,c),k=h.height;d.chart.marginLeft!=parseInt(a.chart.chartleftmargin,10)&&(l=!0);d.chart.marginRight!=parseInt(a.chart.chartrightmargin,10)&&(S=!0);F=j-f;switch(t){case "none":y=
z=!0;D&&(q=M?300:270,h=s,s=r,r=h,y=!0);break;case "rotate":q=M?300:270;h=s;s=r;r=h;y=!0;break;case "stagger":x=y=!0;a=Math.floor((c-C)/s);a<e&&(e=a);break;default:D&&(q=M?300:270,h=s,s=r,r=h)}D=0;f=b.plotLines;for(a=f.length;D<a;D+=1)(h=f[D])&&h.label&&typeof h.label.text!==ta&&L.push(h);f=b.plotBands;D=0;for(a=f.length;D<a;D+=1)(h=f[D])&&h.label&&typeof h.label.text!==ta&&L.push(h);f=b.categories||[];D=0;for(a=f.length;D<a;D+=1)U.push({value:D,label:{text:f[D]}});D=U.length-1;a=U.length;x&&(e>a?
e=a:e<2&&(e=2));if(a){b.scroll&&b.scroll.viewPortMin&&b.scroll.viewPortMax?(R=b.scroll.viewPortMin,h=b.scroll.viewPortMax,S=l=!1):(R=b.min,h=b.max);N=(U[D].value-U[0].value)*O;N=Math.max(K,N/(T-1));K=(U[0].value-R)*O;O*=h-U[D].value;t==="auto"?N<g&&(q=M?300:270,h=s,s=r,r=h,y=!0):t==="stagger"&&(N*=e);t=(K+E)*2;if((g=f[0].label)&&g.text)g.style&&A.setStyle(g.style),g=Math.min(N,A.getOriSize(g.text).width+4),g>t&&(W=(g-t)/2);t=(O+P)*2;if((g=f[D].label)&&g.text)g.style&&A.setStyle(g.style),g=Math.min(N,
A.getOriSize(g.text).width+4),g>t&&(X=(g-t)/2);P=W+X;P>0&&(F>P?(l=(l=X*j/(X+j))?l+4:0,d.chart.marginRight+=l,j-=l,l=(l=W*j/(W+j))?l+4:0,d.chart.marginLeft+=l,j-=l):W<X?F>=X&&S?(l=(l=X*j/(X+j))?l+4:0,d.chart.marginRight+=l,j-=l):l&&(l=(l=W*j/(W+j))?l+4:0,d.chart.marginLeft+=l,j-=l):F>=W&&l?(l=(l=W*j/(W+j))?l+4:0,d.chart.marginLeft+=l,j-=l):S&&(l=(l=X*j/(X+j))?l+4:0,d.chart.marginRight+=l,j-=l));!x&&!z&&(i?(N*=i,N=Math.max(N,r)):(w=Math.ceil(r/N),N*=w));for(i=0;i<a;i+=1)if(h=U[i],i%w&&h.label)h.label.text=
u;else if(h&&h.label&&J(h.label.text)!==void 0){g=h.label;if(g.style&&g.style!==m)m=g.style,A.setStyle(m);if(q&&z)l=A.getOriSize(g.text),v.w=mathMax(v.w,l.width+4),v.h=mathMax(v.h,l.height);else if(!z)l=q||x?A.getOriSize(g.text):A.getSmartText(g.text,N-4,c,y),v.w=Math.max(v.w,l.width+4),v.h=Math.max(v.h,l.height)}}i=0;for(a=L.length;i<a;i+=1)if((h=L[i])&&h.label&&J(h.label.text)!==void 0){g=h.label;if(g.style&&g.style!==m)m=g.style,A.setStyle(m);l=A.getOriSize(g.text);g.verticalAlign===da?V=mathMax(V,
l.height):Q=mathMax(Q,l.height)}b.scroll&&b.scroll.enabled&&!q&&!z&&(i=v.w/2,d.chart.marginLeft<i&&(l=i-d.chart.marginLeft,F>l&&(j-=l,F-=l,d.chart.marginLeft+=l)),d.chart.marginRight<i&&(l=i-d.chart.marginRight,F>l&&(j-=l,d.chart.marginRight+=l)));if(z){if(F=s,q)F=v.w}else F=q?v.w:x?e*s:v.h;F>0&&(Y+=G+F);k>0&&(Y+=k+$);v=Q+Y+2;v>c&&(c=v-c,$>c?($-=c,c=0):(c-=$,$=0,G>c?(G-=c,c=0):(c-=G,G=0)),Q>c?Q-=c:(Q>0&&(c-=Q,Q=0),c>0&&(V>c?V-=c:(V>0&&(c-=V,V=0),c>0&&((h=k-C)>c?k-=c:(c-=h,k=C,c>0&&((h=F-s)>c?F-=c:
(c-=h,F=s,c>0&&(c-=k+$,k=0,c>0&&(c-=F,F=0,c>0&&(G-=c)))))))))));G+=B;C=F+G;c=p.is3d?-d.chart.xDepth:0;a=U.length;v=0;q?(s=N,x=F-4,b.labels.rotation=q,b.labels.align="right",b.labels.y=G-B+4,b.labels.x=r/2):x?x=N*e-4:(s=F,x=N-4);for(i=0;i<a;i+=w)if((h=U[i])&&h.label&&J(h.label.text)!==void 0){g=h.label;if(g.style&&g.style!==m)m=g.style,A.setStyle(m);if(!z)l=A.getSmartText(g.text,x,s,y),b.categories[i]=l.text;v+=1}a=L.length;for(i=q=r=0;i<a;i+=1)if((h=L[i].plotObj?L[i].plotObj:L[i])&&h.label&&J(h.label.text)!==
void 0){g=h.label;if(g.style&&g.style!==m)m=g.style,A.setStyle(m);g.verticalAlign===da?(l=A.getSmartText(g.text,j,V,!0),q=Math.max(q,l.height),g.text=l.text,g.y=C+A.getOriSize("W").height,g.x=c):(l=A.getSmartText(g.text,j,Q,!0),r=Math.max(r,l.height),g.text=l.text,g.y=-(Q-A.getOriSize("W").height+G+2))}if(k>0)A.setStyle(b.title.style),h=A.getSmartText(b.title.text,j,k),b.title.text=h.text,b.title.margin=C+q+$;Y=q;if(F>0)p.horizontalAxisHeight=G+F-B,Y+=p.horizontalAxisHeight;k>0&&(Y+=k+$);d.chart.marginBottom+=
Y;r>0&&(d.chart.marginTop+=r,Y+=r);return Y},creditLabel:!0,defaultPlotShadow:1},c.msline);c("ssgrid",{standaloneInit:!0,defaultSeriesType:"ssgrid",chart:function(){var b=this.containerElement,e=this.dataObj,d=this.chartInstance,e=oa({},e);e.chart=e.chart||e.graph||{};delete e.graph;var a,c,o,f=0,m,l,h=[],i=e.chart,B=e.data,E=B&&B.length,e=this.smartLabel,r=this.numberFormatter,t=b.offsetHeight,q=b.offsetWidth,k={},s=f=0,f=(i.palette>0&&i.palette<6?i.palette:n(this.paletteIndex,1))-1,b={chart:{renderTo:b,
ignoreHiddenSeries:!1,events:{},spacingTop:0,spacingRight:0,spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",style:{fontFamily:g(i.basefont,"Verdana"),fontSize:qa(i.basefontsize,20)+ka,color:g(i.basefontcolor,x.baseFontColor[f]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:ia},labels:{smartLabel:e},colors:["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526",
"B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:"FusionCharts",enabled:this.creditLabel},legend:{enabled:!1},series:[],subtitle:{text:u},title:{text:u},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},H=b.colors,C=b.colors.length,v=0,y=m=c=0,s=a=l=0;c=d.jsVars.cfgStore;d=b.chart;ga(b.chart.style);k.showPercentValues=
n(c.showpercentvalues,i.showpercentvalues,0);k.numberItemsPerPage=g(c.numberitemsperpage,i.numberitemsperpage);k.showShadow=n(c.showshadow,i.showshadow,0);k.baseFont=g(c.basefont,i.basefont,"Verdana");o=qa(c.basefontsize,i.basefontsize,10);k.baseFontSize=o+ka;k.baseFontColor=w(g(c.basefontcolor,i.basefontcolor,x.baseFontColor[f]));k.alternateRowBgColor=w(g(c.alternaterowbgcolor,i.alternaterowbgcolor,x.altHGridColor[f]));k.alternateRowBgAlpha=g(c.alternaterowbgalpha,i.alternaterowbgalpha,x.altHGridAlpha[f])+
u;k.listRowDividerThickness=n(c.listrowdividerthickness,i.listrowdividerthickness,1);k.listRowDividerColor=w(g(c.listrowdividercolor,i.listrowdividercolor,x.borderColor[f]));k.listRowDividerAlpha=n(c.listrowdivideralpha,i.listrowdivideralpha,x.altHGridAlpha[f])+15+u;k.colorBoxWidth=n(c.colorboxwidth,i.colorboxwidth,8);k.colorBoxHeight=n(c.colorboxheight,i.colorboxheight,8);k.navButtonRadius=n(c.navbuttonradius,i.navbuttonradius,7);k.navButtonColor=w(g(c.navbuttoncolor,i.navbuttoncolor,x.canvasBorderColor[f]));
k.navButtonHoverColor=w(g(c.navbuttonhovercolor,i.navbuttonhovercolor,x.altHGridColor[f]));k.textVerticalPadding=n(c.textverticalpadding,i.textverticalpadding,3);k.navButtonPadding=n(c.navbuttonpadding,i.navbuttonpadding,5);k.colorBoxPadding=n(c.colorboxpadding,i.colorboxpadding,10);k.valueColumnPadding=n(c.valuecolumnpadding,i.valuecolumnpadding,10);k.nameColumnPadding=n(c.namecolumnpadding,i.namecolumnpadding,5);k.borderThickness=n(c.borderthickness,i.borderthickness,1);k.borderColor=w(g(c.bordercolor,
i.bordercolor,x.borderColor[f]));k.borderAlpha=g(c.borderalpha,i.borderalpha,x.borderAlpha[f])+u;k.bgColor=g(c.bgcolor,i.bgcolor,"FFFFFF");k.bgAlpha=g(c.bgalpha,i.bgalpha,M);k.bgRatio=g(c.bgratio,i.bgratio,M);k.bgAngle=g(c.bgangle,i.bgangle,O);d.borderRadius=k.borderThickness/16;d.borderWidth=k.borderThickness;d.borderColor={FCcolor:{color:k.borderColor,alpha:k.borderAlpha}};d.backgroundColor={FCcolor:{color:k.bgColor,alpha:k.bgAlpha,ratio:k.bgRatio,angle:k.bgAngle}};o={fontFamily:k.baseFont,fontSize:k.baseFontSize,
color:k.baseFontColor};ga(o);e.setStyle(o);for(f=0;f<E;f+=1)if(a=B[f],m=r.getCleanValue(a.value),l=R(ba(a.label,a.name)),c=w(g(a.color,H[f%C])),g(a.alpha,i.plotfillalpha,M),l!=u||m!=null)h.push({value:m,label:l,color:c}),v+=m,s+=1;for(f=0;f<s;f+=1)a=h[f],m=a.value,a.dataLabel=a.label,a.displayValue=k.showPercentValues?r.percentValue(m/v*100):r.dataLabels(m),B=e.getOriSize(a.displayValue),y=Math.max(y,B.width+k.valueColumnPadding);k.numberItemsPerPage?k.numberItemsPerPage>=s?(k.numberItemsPerPage=
s,m=t/k.numberItemsPerPage,c=s):(r=t,r-=2*(k.navButtonPadding+k.navButtonRadius),c=k.numberItemsPerPage,m=r/c):(f=parseInt(o.lineHeight,10),f+=2*k.textVerticalPadding,f=Math.max(f,k.colorBoxHeight),t/f>=s?(m=t/s,c=s):(r=t,r-=2*(k.navButtonPadding+k.navButtonRadius),c=Math.floor(r/f),m=r/c));l=q-k.colorBoxPadding-k.colorBoxWidth-k.nameColumnPadding-y-k.valueColumnPadding;a=k.colorBoxPadding+k.colorBoxWidth+k.nameColumnPadding;d.height=t;d.width=q;d.rowHeight=m;d.labelX=a;d.colorBoxWidth=k.colorBoxWidth;
d.colorBoxHeight=k.colorBoxHeight;d.colorBoxX=k.colorBoxPadding;d.valueX=k.colorBoxPadding+k.colorBoxWidth+k.nameColumnPadding+l+k.valueColumnPadding;d.valueColumnPadding=k.valueColumnPadding;d.textStyle=o;d.listRowDividerAttr={"stroke-width":k.listRowDividerThickness,stroke:{FCcolor:{color:k.listRowDividerColor,alpha:k.listRowDividerAlpha}}};d.alternateRowColor={FCcolor:{color:k.alternateRowBgColor,alpha:k.alternateRowBgAlpha}};d.navButtonRadius=k.navButtonRadius;d.navButtonPadding=k.navButtonPadding;
d.navButtonColor=k.navButtonColor;d.navButtonHoverColor=k.navButtonHoverColor;d.lineHeight=parseInt(o.lineHeight,10);t=[];k=0;r=!0;for(f=0;f<s&c!=0;f+=1)f%c==0&&(t.push({data:[],visible:r}),r=!1,k+=1),a=h[f],t[k-1].data.push({label:e.getSmartText(a.dataLabel,l,m).text,displayValue:a.displayValue,y:a.value,color:a.color});b.series=t;b.exporting.enabled=i.exportenabled=="1"?!0:!1;b.exporting.buttons.exportButton.enabled=i.exportshowmenuitem=="0"?!1:!0;b.exporting.filename=i.exportfilename?i.exportfilename:
"FusionCharts";b.exporting.width=q;return b},creditLabel:!0},c.base);m.Highcharts.Renderer.prototype.symbols.zoomOutIcon=function(b,c,d){b-=1;c-=1;d-=0.5;var a=43*K,j=48*K,g=b+d*T(a),a=c+d*E(a),f=b+d*T(j),j=c+d*E(j),m=45*K,l=g+4*T(m),h=a+4*E(m),i=f+4*T(m),m=j+4*E(m);return["M",g,a,"A",d,d,0,1,0,f,j,"Z","M",g+1,a+1,"L",l,h,i,m,f+1,j+1,"Z","M",b-2,c,"L",b+2,c,"Z"]};m.Highcharts.Renderer.prototype.symbols.resetIcon=function(b,c,d){b-=0.25;var a=c-0.5,g=310*K,m=225*K,c=b+d*T(g),g=a+d*E(g);b+=d*T(m);a+=
d*E(m);return["M",c+1,g,"A",d,d,0,1,1,b+1,a,"M",b,a,"L",b+3.5*T(50*K),a+3.5*E(50*K),b+3.5*T(125*K),a+3.5*E(125*K),b,a,"Z"]}}})();
