ALTER TABLE [dbo].[TBL_CONTACTS] ADD [FACEBOOKID] [varchar](150) NULL
ALTER TABLE [dbo].[TBL_CONTACTS] ADD [TWITTERID] [varchar](150) NULL
ALTER TABLE [dbo].[TBL_CONTACTS] ADD [LINKEDINID] [varchar](150) NULL
 
ALTER TABLE [dbo].[TBL_COMPANIES] ADD [FACEBOOKID] [varchar](50) NULL
ALTER TABLE [dbo].[TBL_COMPANIES] ADD [TWITTERID] [varchar](50) NULL
ALTER TABLE [dbo].[TBL_COMPANIES] ADD [LINKEDINID] [varchar](50) NULL
 